# Generated by Django 6.0.5 on 2026-07-14 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiqSavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiqTermDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiqTimeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la banda (Ej. 1M, 2M, 3M, 1A)', max_length=50)),
                ('order', models.IntegerField(help_text='Orden de visualización')),
                ('days_start', models.IntegerField(blank=True, help_text='Límite inferior en días', null=True)),
                ('days_end', models.IntegerField(blank=True, help_text='Límite superior en días', null=True)),
            ],
            options={
                'verbose_name': 'Banda Temporal',
                'verbose_name_plural': 'Bandas Temporales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarteraPasivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('of', models.CharField(blank=True, max_length=50, null=True)),
                ('id_socio', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ahorro', models.CharField(blank=True, max_length=50, null=True)),
                ('socio', models.CharField(blank=True, max_length=255, null=True)),
                ('apertura', models.DateField(blank=True, null=True)),
                ('ofic_apertura', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('captador', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.CharField(blank=True, max_length=150, null=True)),
                ('tim', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tea', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ult_mov', models.DateField(blank=True, null=True)),
                ('vence', models.DateField(blank=True, null=True)),
                ('plz', models.IntegerField(blank=True, default=0, null=True)),
                ('ah_vinc', models.IntegerField(blank=True, default=0, null=True)),
                ('mon', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('agencia_calc', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_asesor', models.CharField(blank=True, max_length=100, null=True)),
                ('producto_agrupado', models.CharField(blank=True, max_length=100, null=True)),
                ('saldo_dpf', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('saldo_prog', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('saldo_ctas_libre', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('trea', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('plazo_dpf', models.IntegerField(blank=True, default=0, null=True)),
                ('p_vence2', models.CharField(blank=True, max_length=100, null=True)),
                ('adm_agen', models.CharField(blank=True, max_length=100, null=True)),
                ('id_compuesto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_corte', 'id_ahorro'], name='liquidity_r_fecha_c_501f72_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiqBalanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Fecha de corte del balance')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Éxito'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('period',)},
            },
        ),
        migrations.CreateModel(
            name='LiqLiabilityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_type', models.CharField(blank=True, max_length=100, null=True)),
                ('liquidity_item', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('liquidity_band', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'liquidity_band'], name='liquidity_r_period_aa8a92_idx'), models.Index(fields=['period', 'liquidity_item'], name='liquidity_r_period_6d190c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiqBalanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('account_code', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='liquidity_risk.liqbalanceupload')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'account_code'], name='liquidity_r_period_e16c13_idx')],
            },
        ),
    ]
