# Generated by Django 6.0.4 on 2026-04-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositor_name', models.CharField(max_length=255, verbose_name='Nombre del Depositante')),
                ('depositor_segment', models.CharField(blank=True, max_length=100, verbose_name='Segmento')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo de Depósitos')),
                ('percentage_of_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% del Total')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Reporte')),
            ],
            options={
                'verbose_name': 'Concentración de Depósito',
                'verbose_name_plural': 'Concentración de Depósitos',
            },
        ),
        migrations.CreateModel(
            name='LiquidityGapBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Banda')),
                ('start_days', models.IntegerField(verbose_name='Días Inicio')),
                ('end_days', models.IntegerField(verbose_name='Días Fin')),
            ],
            options={
                'verbose_name': 'Banda de Liquidez',
                'verbose_name_plural': 'Bandas de Liquidez',
            },
        ),
        migrations.CreateModel(
            name='LiquidityScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Escenario')),
                ('description', models.TextField()),
                ('is_stress_test', models.BooleanField(default=False, verbose_name='Es Prueba de Estrés')),
            ],
            options={
                'verbose_name': 'Escenario de Liquidez',
                'verbose_name_plural': 'Escenarios de Liquidez',
            },
        ),
    ]
