# Generated by Django 5.2.7 on 2026-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositconcentration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liquiditygapband',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liquidityscenario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LiabilityOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=100, verbose_name='Agencia')),
                ('opening_agency', models.CharField(max_length=100, verbose_name='Agencia de Apertura')),
                ('customer_code', models.CharField(max_length=50, verbose_name='Código Socio/Cliente')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Apellidos y Nombres')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Apertura')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('opening_code', models.CharField(max_length=50, verbose_name='Código de Apertura')),
                ('product', models.CharField(max_length=255, verbose_name='Producto')),
                ('currency', models.CharField(max_length=50, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo')),
                ('tea', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TEA')),
                ('tem', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TEM')),
                ('term', models.IntegerField(blank=True, null=True, verbose_name='Plazo')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('collector', models.CharField(blank=True, max_length=100, verbose_name='Captador')),
                ('last_movement_date', models.DateField(blank=True, null=True, verbose_name='Última Fecha Movimiento')),
                ('load_date', models.DateField(verbose_name='Fecha de Corte')),
            ],
            options={
                'verbose_name': 'Operación de Pasivo',
                'verbose_name_plural': 'Operaciones de Pasivos',
                'unique_together': {('customer_code', 'opening_code', 'load_date')},
            },
        ),
    ]
