# Generated by Django 6.0.5 on 2026-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbsParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=100, verbose_name='Indicador / Ratio')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Interno')),
                ('sign', models.CharField(max_length=10, verbose_name='Signo')),
                ('limit_value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Límite Normativo')),
                ('limit_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Parámetro SBS',
                'verbose_name_plural': 'Parámetros SBS',
            },
        ),
        migrations.CreateModel(
            name='VolatileBalanceLar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='F. Cálculo')),
                ('segment', models.CharField(max_length=100, verbose_name='Segmento')),
                ('currency', models.CharField(default='MN', max_length=20, verbose_name='Moneda')),
                ('total_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo Total')),
                ('volatile_balance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo Volátil')),
                ('volatility_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% Volatilidad')),
                ('executed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ejecutado por')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='F. Ejecución')),
            ],
            options={
                'verbose_name': 'Saldo Volátil LaR',
                'verbose_name_plural': 'Saldos Volátiles LaR',
                'unique_together': {('period', 'segment', 'currency')},
            },
        ),
    ]
