# Generated by Django 5.2.7 on 2026-05-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0002_alter_depositconcentration_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(unique=True, verbose_name='Fecha de Corte')),
                ('renewal_rate_deposits', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='Tasa de Renovación Depósitos (%)')),
                ('recovery_rate_credit', models.DecimalField(decimal_places=2, default=95.0, max_digits=5, verbose_name='Tasa de Recuperación Cartera (%)')),
                ('withdrawal_rate_savings', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Tasa de Retiro Ahorros (%)')),
                ('shock_withdrawal_savings', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Shock Retiro Ahorros (%)')),
                ('shock_recovery_credit', models.DecimalField(decimal_places=2, default=-15.0, max_digits=5, verbose_name='Shock Recuperación Cartera (%)')),
            ],
            options={
                'verbose_name': 'Parámetro de Liquidez',
                'verbose_name_plural': 'Parámetros de Liquidez',
            },
        ),
        migrations.CreateModel(
            name='LiquidityFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(verbose_name='Fecha de Corte')),
                ('flow_type', models.CharField(choices=[('IN', 'Entrada (Activos)'), ('OUT', 'Salida (Pasivos)')], max_length=3, verbose_name='Tipo de Flujo')),
                ('contractual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Contractual')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Esperado')),
                ('stress_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Estrés')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liquiditygapband', verbose_name='Banda Temporal')),
            ],
            options={
                'verbose_name': 'Flujo de Liquidez',
                'verbose_name_plural': 'Flujos de Liquidez',
                'unique_together': {('load_date', 'band', 'flow_type')},
            },
        ),
    ]
