# Generated by Django 6.0.5 on 2026-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0002_sbsparameter_volatilebalancelar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carterapasivocarga',
            name='fecha_corte',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='volatilebalancelar',
            name='period',
            field=models.DateField(db_index=True, verbose_name='F. Cálculo'),
        ),
    ]
