# Generated by Django 5.2.7 on 2026-05-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0003_liquidityparameter_liquidityflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(unique=True, verbose_name='Fecha de Corte')),
                ('vigente', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cartera Vigente')),
                ('refinanciada', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cartera Refinanciada')),
                ('vencida', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cartera Vencida')),
                ('judicial', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cartera Judicial')),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cartera Total')),
                ('ahorro', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Depósitos de Ahorro')),
                ('plazo_fijo', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Depósitos a Plazo')),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Depósitos')),
                ('delinquency_index', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Índice de Morosidad (%)')),
                ('liquidity_degree', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Grado de Liquidez (Créditos/Depósitos)')),
                ('deposit_volatility', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Volatilidad de Depósitos (%)')),
                ('monthly_variation', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Variación Mensual Depósitos (%)')),
            ],
            options={
                'verbose_name': 'Métrica de Liquidez Mensual',
                'verbose_name_plural': 'Métricas de Liquidez Mensuales',
                'ordering': ['-load_date'],
            },
        ),
    ]
