# Generated by Django 5.2.7 on 2026-05-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0004_liquiditymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(verbose_name='Fecha de Corte')),
                ('indicator_name', models.CharField(max_length=100, verbose_name='Indicador')),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor Actual')),
                ('limit_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor Límite')),
                ('severity', models.CharField(default='Warning', max_length=20, verbose_name='Severidad')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
            ],
            options={
                'verbose_name': 'Alerta de Liquidez',
                'verbose_name_plural': 'Alertas de Liquidez',
                'ordering': ['-load_date'],
            },
        ),
        migrations.CreateModel(
            name='LiquidityLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=100, verbose_name='Indicador')),
                ('limit_type', models.CharField(choices=[('MAX', 'Máximo'), ('MIN', 'Mínimo')], max_length=3, verbose_name='Tipo de Límite')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor Umbral')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Límite de Liquidez',
                'verbose_name_plural': 'Límites de Liquidez',
            },
        ),
    ]
