# Generated by Django 5.2.7 on 2026-05-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0005_liquidityalert_liquiditylimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidityflow',
            name='agency',
            field=models.CharField(default='TODAS', max_length=100, verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='liquidityflow',
            name='currency',
            field=models.CharField(default='CONSOLIDADO', max_length=50, verbose_name='Moneda'),
        ),
    ]
