# Generated by Django 5.2.7 on 2026-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0006_liquidityflow_agency_liquidityflow_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityContingencyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('NORMAL', 'Normal (Verde)'), ('PREVENTIVE', 'Preventivo (Amarillo)'), ('RECOVERY', 'Recuperación (Naranja)'), ('CRITICAL', 'Crítico (Rojo)')], max_length=20, unique=True, verbose_name='Nivel de Alerta')),
                ('description', models.TextField(verbose_name='Descripción del Escenario')),
                ('triggers', models.TextField(verbose_name='Disparadores / Triggers')),
                ('actions', models.TextField(verbose_name='Acciones de Mitigación')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo actualmente')),
                ('last_activation', models.DateTimeField(blank=True, null=True, verbose_name='Última Activación')),
            ],
            options={
                'verbose_name': 'Plan de Contingencia',
                'verbose_name_plural': 'Planes de Contingencia',
            },
        ),
        migrations.RemoveField(
            model_name='liquidityscenario',
            name='is_stress_test',
        ),
        migrations.AddField(
            model_name='liquidityscenario',
            name='recovery_shock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Shock Recuperación (%)'),
        ),
        migrations.AddField(
            model_name='liquidityscenario',
            name='renewal_shock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Shock No Renovación (%)'),
        ),
        migrations.AddField(
            model_name='liquidityscenario',
            name='withdrawal_shock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Shock Retiro (%)'),
        ),
        migrations.AlterField(
            model_name='liquidityscenario',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='liquidityscenario',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Escenario'),
        ),
    ]
