# Generated by Django 5.2.7 on 2026-05-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0007_liquiditycontingencyplan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidityflow',
            unique_together={('load_date', 'band', 'flow_type', 'currency', 'agency')},
        ),
    ]
