# Generated by Django 5.2.7 on 2026-05-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0008_alter_liquidityflow_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALCOSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_number', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('agreements', models.TextField()),
                ('contingency_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LiquidAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Activo')),
                ('asset_type', models.CharField(choices=[('CASH', 'Caja y Efectivo'), ('BANKS', 'Bancos y Corresponsales'), ('BCRP', 'Depósitos en BCRP'), ('INVESTMENTS_HQLA', 'Inversiones Negociables HQLA')], max_length=20, verbose_name='Tipo de Activo')),
                ('currency', models.CharField(max_length=50, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('haircut', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Castigo / Haircut (%)')),
                ('load_date', models.DateField(db_index=True, verbose_name='Fecha de Corte')),
            ],
        ),
        migrations.AlterModelOptions(
            name='depositconcentration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='liquidityalert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='liquiditycontingencyplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='liquidityflow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='liquiditygapband',
            options={'ordering': ['start_days'], 'verbose_name': 'Banda de Liquidez', 'verbose_name_plural': 'Bandas de Liquidez'},
        ),
        migrations.AlterModelOptions(
            name='liquiditylimit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='liquiditymetric',
            options={},
        ),
        migrations.AlterModelOptions(
            name='liquidityparameter',
            options={},
        ),
        migrations.RenameField(
            model_name='liquidityscenario',
            old_name='renewal_shock',
            new_name='non_renewal_shock',
        ),
        migrations.AlterUniqueTogether(
            name='liquidityflow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='depositconcentration',
            name='depositor_segment',
        ),
        # MOVED ADD FIELDS BEFORE UNIQUE TOGETHER
        migrations.AddField(
            model_name='liabilityoperation',
            name='operation_code',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Código Operación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liabilityoperation',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Tasa (%)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='liabilityoperation',
            unique_together={('operation_code', 'load_date')},
        ),
        migrations.RemoveField(
            model_name='liquiditycontingencyplan',
            name='last_activation',
        ),
        migrations.RemoveField(
            model_name='liquiditylimit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='liquiditymetric',
            name='ahorro',
        ),
        migrations.RemoveField(
            model_name='liquiditymetric',
            name='judicial',
        ),
        migrations.RemoveField(
            model_name='liquiditymetric',
            name='plazo_fijo',
        ),
        migrations.RemoveField(
            model_name='liquiditymetric',
            name='refinanciada',
        ),
        migrations.RemoveField(
            model_name='liquidityparameter',
            name='shock_recovery_credit',
        ),
        migrations.RemoveField(
            model_name='liquidityparameter',
            name='shock_withdrawal_savings',
        ),
        migrations.RemoveField(
            model_name='liquidityparameter',
            name='withdrawal_rate_savings',
        ),
        migrations.AddField(
            model_name='liquidityflow',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liquidityscenario'),
        ),
        migrations.AddField(
            model_name='liquiditymetric',
            name='currency',
            field=models.CharField(default='CONSOLIDADO', max_length=50, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='liquiditymetric',
            name='liquidity_ratio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Ratio de Liquidez (%)'),
        ),
        migrations.AddField(
            model_name='liquiditymetric',
            name='r_coverage_liquidity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='RCL (%)'),
        ),
        migrations.AddField(
            model_name='liquidityparameter',
            name='lar_confidence_level',
            field=models.DecimalField(decimal_places=2, default=95.0, max_digits=5, verbose_name='Nivel de Confianza LaR (%)'),
        ),
        migrations.AddField(
            model_name='liquidityparameter',
            name='lar_horizon_days',
            field=models.IntegerField(default=30, verbose_name='Horizonte LaR (Días)'),
        ),
        migrations.AddField(
            model_name='liquidityscenario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='liquidityscenario',
            name='scenario_type',
            field=models.CharField(choices=[('CONTRACTUAL', 'Contractual'), ('EXPECTED', 'Esperado'), ('ADVERSE', 'Adverso'), ('SEVERE', 'Severo')], default='CONTRACTUAL', max_length=20, verbose_name='Tipo de Escenario'),
        ),
        migrations.AlterField(
            model_name='depositconcentration',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='depositconcentration',
            name='percentage_of_total',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Total'),
        ),
        migrations.AlterField(
            model_name='depositconcentration',
            name='report_date',
            field=models.DateField(verbose_name='Fecha Reporte'),
        ),
        migrations.AlterField(
            model_name='liabilityoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Inicial'),
        ),
        migrations.AlterField(
            model_name='liabilityoperation',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo Actual'),
        ),
        migrations.AlterField(
            model_name='liabilityoperation',
            name='load_date',
            field=models.DateField(db_index=True, verbose_name='Fecha de Corte'),
        ),
        migrations.AlterField(
            model_name='liquiditycontingencyplan',
            name='actions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='liquiditycontingencyplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='liquiditycontingencyplan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='liquiditycontingencyplan',
            name='level',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PREVENTIVE', 'Preventivo'), ('RECOVERY', 'Recuperación'), ('CRITICAL', 'Crítico')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='liquiditycontingencyplan',
            name='triggers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='liquidityflow',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liquiditygapband'),
        ),
        migrations.AlterField(
            model_name='liquiditylimit',
            name='indicator_name',
            field=models.CharField(max_length=100, verbose_name='Nombre de Indicador'),
        ),
        migrations.AlterField(
            model_name='liquiditylimit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='liquiditylimit',
            name='limit_type',
            field=models.CharField(choices=[('MAX', 'Máximo'), ('MIN', 'Mínimo')], max_length=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='liquiditymetric',
            name='liquidity_degree',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Grado de Liquidez'),
        ),
        migrations.AlterField(
            model_name='liquiditymetric',
            name='monthly_variation',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Variación Mensual (%)'),
        ),
        migrations.AlterField(
            model_name='liquidityscenario',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='liquidityscenario',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre de Escenario'),
        ),
        migrations.AlterField(
            model_name='liquidityscenario',
            name='recovery_shock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Shock Recuperación Cartera (%)'),
        ),
        migrations.AlterField(
            model_name='liquidityscenario',
            name='withdrawal_shock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Shock Retiro Depósitos (%)'),
        ),
        migrations.CreateModel(
            name='HistoricalDepositBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('currency', models.CharField(max_length=50, verbose_name='Moneda')),
                ('product_type', models.CharField(max_length=100, verbose_name='Tipo de Producto')),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo Total')),
            ],
            options={
                'unique_together': {('date', 'currency', 'product_type')},
            },
        ),
        migrations.CreateModel(
            name='LiabilitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento Cuota')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Capital')),
                ('interest', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Interés')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total')),
                ('load_date', models.DateField(db_index=True, verbose_name='Fecha de Corte')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='liquidity_risk.liabilityoperation')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityGapCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(db_index=True, verbose_name='Fecha de Corte')),
                ('currency', models.CharField(max_length=50, verbose_name='Moneda')),
                ('inflows', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Ingresos')),
                ('outflows', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Egresos')),
                ('marginal_gap', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Brecha Marginal')),
                ('accumulated_gap', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Brecha Acumulada')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liquiditygapband')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liquidityscenario')),
            ],
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='age',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='last_movement_date',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='opening_agency',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='opening_code',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='tea',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='tem',
        ),
        migrations.RemoveField(
            model_name='liabilityoperation',
            name='user',
        ),
    ]
