# Generated by Django 5.2.7 on 2026-05-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0009_alcosession_auditlog_liquidasset_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liabilityoperation',
            unique_together=set(),
        ),
    ]
