# Generated by Django 5.2.7 on 2026-05-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0010_alter_liabilityoperation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liabilityoperation',
            unique_together={('operation_code', 'load_date')},
        ),
    ]
