# Generated by Django 5.2.7 on 2026-05-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0011_alter_liabilityoperation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquiditylimit',
            name='indicator',
            field=models.CharField(choices=[('RL', 'Ratio de Liquidez'), ('RCL', 'Ratio de Cobertura de Liquidez'), ('CONC', 'Concentración de Depositantes'), ('MOROSIDAD', 'Índice de Morosidad')], default='RL', max_length=20, verbose_name='Indicador'),
        ),
    ]
