# Generated by Django 5.2.7 on 2026-05-14 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0013_alter_alcosession_id_alter_auditlog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiqAccountMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20, unique=True, verbose_name='Código Contable')),
                ('liquidity_item', models.CharField(max_length=100, verbose_name='Rubro de Liquidez')),
                ('assigned_band', models.CharField(blank=True, max_length=50, verbose_name='Banda Asignada')),
            ],
        ),
        migrations.CreateModel(
            name='LiqAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Periodo')),
                ('indicator_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('severity', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiqAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiqAvailableFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('ifi', models.CharField(max_length=255, verbose_name='Institución Financiera')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Restringido')),
            ],
        ),
        migrations.CreateModel(
            name='LiqBalanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('account_code', models.CharField(max_length=20, verbose_name='Código Contable')),
                ('account_name', models.CharField(max_length=255, verbose_name='Nombre Cuenta')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo')),
                ('nature', models.CharField(choices=[('D', 'Deudora'), ('A', 'Acreedora')], max_length=1, verbose_name='Naturaleza')),
            ],
            options={
                'verbose_name': 'Detalle de Balance',
            },
        ),
        migrations.CreateModel(
            name='LiqBalanceUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('file_source', models.FileField(upload_to='liquidity/balance/', verbose_name='Archivo Fuente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALIDATING', 'Validando'), ('SUCCESS', 'Cargado con éxito'), ('ERROR', 'Error'), ('APPROVED', 'Aprobado')], default='PENDING', max_length=20)),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de Balance',
                'unique_together': {('period',)},
            },
        ),
        migrations.CreateModel(
            name='LiqBreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=255, verbose_name='Responsable')),
                ('corrective_action', models.TextField(verbose_name='Acción Correctiva')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liqalert')),
            ],
        ),
        migrations.CreateModel(
            name='LiqConcentrationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('item_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo')),
                ('participation_pct', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Participación (%)')),
            ],
        ),
        migrations.CreateModel(
            name='LiqContingencyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('responsible', models.CharField(max_length=255)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqContingencyActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_event', models.TextField(verbose_name='Evento Gatillo')),
                ('status', models.CharField(default='OPEN', max_length=20, verbose_name='Estado')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqContingencyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Plan')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('customer_id', models.CharField(max_length=50, verbose_name='Socio')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo Aportes')),
                ('participation_pct', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Participación (%)')),
                ('ranking', models.IntegerField(verbose_name='Ranking')),
            ],
        ),
        migrations.CreateModel(
            name='LiqFundingLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('financial_institution', models.CharField(max_length=255, verbose_name='Institución Financiera')),
                ('line_type', models.CharField(max_length=100, verbose_name='Tipo de Línea')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Aprobado')),
                ('used_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Utilizado')),
                ('available_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Disponible')),
                ('approval_date', models.DateField(verbose_name='Fecha Aprobación')),
                ('due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('guarantee', models.CharField(max_length=255, verbose_name='Garantía')),
                ('tea', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TEA (%)')),
                ('tcea', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TCEA (%)')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='LiqGapDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Rubro')),
                ('item_type', models.CharField(choices=[('ACT', 'Activo'), ('PAS', 'Pasivo')], max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
            ],
        ),
        migrations.CreateModel(
            name='LiqGapReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('ifi', models.CharField(max_length=255, verbose_name='Institución Financiera')),
                ('investment_type', models.CharField(max_length=100, verbose_name='Tipo Inversión')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('rating', models.CharField(blank=True, max_length=10, verbose_name='Calificación')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Restringido')),
            ],
        ),
        migrations.CreateModel(
            name='LiqLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=100, verbose_name='Indicador')),
                ('limit_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Mínimo')),
                ('limit_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Máximo')),
                ('early_warning', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Alerta Temprana')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqMonthlyIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Indicador')),
                ('value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor')),
                ('status', models.CharField(default='VERDE', max_length=10, verbose_name='Estado (Semáforo)')),
            ],
        ),
        migrations.CreateModel(
            name='LiqMonthlyPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('liquid_assets', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Activos Líquidos')),
                ('short_term_liabilities', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Pasivos Corto Plazo')),
                ('liquidity_ratio', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Ratio Liquidez (%)')),
                ('adjusted_ratio', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Ratio Ajustado (%)')),
            ],
        ),
        migrations.CreateModel(
            name='LiqPortfolioDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('credit_status', models.CharField(max_length=50, verbose_name='Estado Crédito')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo')),
                ('mora_days', models.IntegerField(verbose_name='Días Mora')),
                ('expected_recovery', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Recuperación Esperada')),
            ],
        ),
        migrations.CreateModel(
            name='LiqReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Reporte')),
                ('report_type', models.CharField(max_length=50)),
                ('period', models.DateField()),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqSavingsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Periodo')),
                ('customer_id', models.CharField(max_length=50, verbose_name='Socio')),
                ('document', models.CharField(max_length=20, verbose_name='Documento')),
                ('account_number', models.CharField(max_length=50, verbose_name='Cuenta')),
                ('product', models.CharField(max_length=100, verbose_name='Producto')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo')),
                ('opening_date', models.DateField(verbose_name='Fecha Apertura')),
                ('last_movement_date', models.DateField(verbose_name='Último Movimiento')),
                ('agency', models.CharField(max_length=100, verbose_name='Agencia')),
                ('segment', models.CharField(max_length=50, verbose_name='Segmento')),
                ('is_major_depositor', models.BooleanField(default=False, verbose_name='Gran Depositante')),
            ],
        ),
        migrations.CreateModel(
            name='LiqSavingsUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('file_source', models.FileField(upload_to='liquidity/savings/', verbose_name='Archivo Fuente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALIDATING', 'Validando'), ('SUCCESS', 'Cargado con éxito'), ('ERROR', 'Error'), ('APPROVED', 'Aprobado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiqStressResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=100)),
                ('base_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('stressed_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('impact', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='LiqStressRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiqStressScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre Escenario')),
                ('description', models.TextField()),
                ('is_custom', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqTermDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Periodo')),
                ('customer_id', models.CharField(max_length=50, verbose_name='Socio')),
                ('document', models.CharField(max_length=20, verbose_name='Documento')),
                ('certificate_number', models.CharField(max_length=50, verbose_name='Certificado')),
                ('product', models.CharField(max_length=100, verbose_name='Producto')),
                ('currency', models.CharField(max_length=10, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa (%)')),
                ('opening_date', models.DateField(verbose_name='Fecha Constitución')),
                ('due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('residual_term', models.IntegerField(verbose_name='Plazo Residual')),
                ('agency', models.CharField(max_length=100, verbose_name='Agencia')),
                ('is_renewable', models.BooleanField(default=False, verbose_name='Renovable')),
                ('is_major_depositor', models.BooleanField(default=False, verbose_name='Gran Depositante')),
            ],
        ),
        migrations.CreateModel(
            name='LiqTermDepositUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('file_source', models.FileField(upload_to='liquidity/dpf/', verbose_name='Archivo Fuente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALIDATING', 'Validando'), ('SUCCESS', 'Cargado con éxito'), ('ERROR', 'Error'), ('APPROVED', 'Aprobado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqTimeBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Banda')),
                ('start_days', models.IntegerField(verbose_name='Días Inicio')),
                ('end_days', models.IntegerField(verbose_name='Días Fin')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ALCOSession',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DepositConcentration',
        ),
        migrations.DeleteModel(
            name='HistoricalDepositBalance',
        ),
        migrations.AlterUniqueTogether(
            name='liabilityoperation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='liabilityschedule',
            name='operation',
        ),
        migrations.DeleteModel(
            name='LiquidAsset',
        ),
        migrations.DeleteModel(
            name='LiquidityAlert',
        ),
        migrations.DeleteModel(
            name='LiquidityContingencyPlan',
        ),
        migrations.RemoveField(
            model_name='liquidityflow',
            name='band',
        ),
        migrations.RemoveField(
            model_name='liquidityflow',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='liquiditygapcalculation',
            name='band',
        ),
        migrations.RemoveField(
            model_name='liquiditygapcalculation',
            name='scenario',
        ),
        migrations.DeleteModel(
            name='LiquidityLimit',
        ),
        migrations.DeleteModel(
            name='LiquidityMetric',
        ),
        migrations.DeleteModel(
            name='LiquidityParameter',
        ),
        migrations.AddField(
            model_name='liqbalancedetail',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='liquidity_risk.liqbalanceupload'),
        ),
        migrations.AddField(
            model_name='liqcontingencyaction',
            name='activation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='liquidity_risk.liqcontingencyactivation'),
        ),
        migrations.AddField(
            model_name='liqcontingencyactivation',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liqcontingencyplan'),
        ),
        migrations.AddField(
            model_name='liqgapdetail',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='liquidity_risk.liqgapreport'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='liquidity_risk.liqsavingsupload'),
        ),
        migrations.AddField(
            model_name='liqstressresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='liquidity_risk.liqstressrun'),
        ),
        migrations.AddField(
            model_name='liqstressrun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liqstressscenario'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='liquidity_risk.liqtermdepositupload'),
        ),
        migrations.AddField(
            model_name='liqgapdetail',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidity_risk.liqtimeband'),
        ),
        migrations.DeleteModel(
            name='LiabilityOperation',
        ),
        migrations.DeleteModel(
            name='LiabilitySchedule',
        ),
        migrations.DeleteModel(
            name='LiquidityFlow',
        ),
        migrations.DeleteModel(
            name='LiquidityGapBand',
        ),
        migrations.DeleteModel(
            name='LiquidityGapCalculation',
        ),
        migrations.DeleteModel(
            name='LiquidityScenario',
        ),
    ]
