# Generated by Django 5.2.7 on 2026-05-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0014_liqaccountmapping_liqalert_liqapproval_liqauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqaccountmapping',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de Cuenta'),
        ),
    ]
