# Generated by Django 5.2.7 on 2026-05-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0015_liqaccountmapping_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqaccountmapping',
            name='plan_model',
            field=models.CharField(default='ESTANDAR', max_length=50, verbose_name='Modelo de Plan'),
        ),
        migrations.AlterField(
            model_name='liqaccountmapping',
            name='account_code',
            field=models.CharField(max_length=20, verbose_name='Código Contable'),
        ),
        migrations.AlterUniqueTogether(
            name='liqaccountmapping',
            unique_together={('plan_model', 'account_code')},
        ),
    ]
