# Generated by Django 5.2.7 on 2026-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0016_liqaccountmapping_plan_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiqAccountPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Modelo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='liqaccountmapping',
            name='plan_model',
            field=models.CharField(default='ESTANDAR', max_length=50, verbose_name='Modelo de Plan (Ref)'),
        ),
    ]
