# Generated by Django 5.2.7 on 2026-05-14 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0017_liqaccountplanmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liqaccountmapping',
            name='plan_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='liquidity_risk.liqaccountplanmodel', verbose_name='Modelo de Plan'),
        ),
    ]
