# Generated by Django 5.2.7 on 2026-05-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0018_alter_liqaccountmapping_plan_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqbalanceupload',
            name='plan_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='liquidity_risk.liqaccountplanmodel', verbose_name='Modelo de Plan'),
        ),
    ]
