# Generated by Django 5.2.7 on 2026-05-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0019_liqbalanceupload_plan_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqbalancedetail',
            name='liquidity_item',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rubro de Liquidez'),
        ),
    ]
