# Generated by Django 5.2.7 on 2026-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0020_liqbalancedetail_liquidity_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqbalanceupload',
            name='currency',
            field=models.CharField(choices=[('MN', 'Soles (MN)'), ('ME', 'Dólares (ME)'), ('MX', 'Integrado (Soles + Dólares)')], default='MN', max_length=2, verbose_name='Moneda'),
        ),
    ]
