# Generated by Django 5.2.7 on 2026-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0021_liqbalanceupload_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiqSbsLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Indicador')),
                ('sign', models.CharField(default='>=', max_length=5, verbose_name='Signo')),
                ('limit_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor Límite')),
                ('is_percentage', models.BooleanField(default=True, verbose_name='Es Porcentaje')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
