# Generated by Django 5.2.7 on 2026-05-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0022_liqsbslimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liqaccountmapping',
            name='assigned_band',
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='account_type',
            field=models.CharField(choices=[('ACT', 'Activo'), ('PAS', 'Pasivo'), ('CON', 'Contingente'), ('PAT', 'Patrimonio')], default='ACT', max_length=3, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='currency',
            field=models.CharField(choices=[('MN', 'Soles'), ('ME', 'Dólares'), ('MX', 'Ambas')], default='MN', max_length=2, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='data_source',
            field=models.CharField(choices=[('BALANCE', 'Balance de Comprobación'), ('AUXILIARY', 'Auxiliar Complementario'), ('CREDIT_RISK', 'Módulo Riesgo Crédito (Solo Lectura)'), ('MANUAL', 'Ingreso Manual')], default='BALANCE', max_length=15, verbose_name='Origen del Dato'),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='default_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liquidity_risk.liqtimeband', verbose_name='Banda por Defecto'),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='distribution_rule',
            field=models.CharField(choices=[('TOTAL', 'Total en Banda Defecto'), ('VOLATILE', 'Volátil (Vencimiento 0-30 días)'), ('SCHEDULE', 'Cronograma Residual (Auxiliar)'), ('STABLE', 'Estable (Bandas Largas)'), ('CUSTOM', 'Regla Personalizada')], default='TOTAL', max_length=20, verbose_name='Regla de Distribución'),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Vigente'),
        ),
    ]
