# Generated by Django 5.2.7 on 2026-05-14 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0023_remove_liqaccountmapping_assigned_band_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiqFundingUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('file_source', models.FileField(upload_to='liquidity/funding/', verbose_name='Archivo Fuente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALIDATING', 'Validando'), ('SUCCESS', 'Cargado con éxito'), ('ERROR', 'Error'), ('APPROVED', 'Aprobado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='liqfundingline',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='liquidity_risk.liqfundingupload'),
        ),
        migrations.CreateModel(
            name='LiqInvestmentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('file_source', models.FileField(upload_to='liquidity/investments/', verbose_name='Archivo Fuente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALIDATING', 'Validando'), ('SUCCESS', 'Cargado con éxito'), ('ERROR', 'Error'), ('APPROVED', 'Aprobado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='liqinvestment',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='liquidity_risk.liqinvestmentupload'),
        ),
    ]
