# Generated by Django 5.2.7 on 2026-05-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0024_liqfundingupload_liqfundingline_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liqbalancedetail',
            name='account_code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Código Contable'),
        ),
        migrations.AlterField(
            model_name='liqbalancedetail',
            name='currency',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='liqbalancedetail',
            name='liquidity_item',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Rubro de Liquidez'),
        ),
        migrations.AlterField(
            model_name='liqsavingsaccount',
            name='currency',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='liqsavingsaccount',
            name='customer_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Socio'),
        ),
        migrations.AlterField(
            model_name='liqsavingsaccount',
            name='period',
            field=models.DateField(db_index=True, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='currency',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='customer_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Socio'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='period',
            field=models.DateField(db_index=True, verbose_name='Periodo'),
        ),
    ]
