# Generated by Django 5.2.7 on 2026-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0025_alter_liqbalancedetail_account_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='captador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Captador'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='created_by_user_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuario Crea'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='customer_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='customer_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='customer_gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='opening_agency',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agencia Apertura'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='captador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Captador'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='created_by_user_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuario Crea'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='customer_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='customer_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='customer_gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='opening_agency',
            field=models.CharField(blank=True, max_length=100, verbose_name='Agencia Apertura'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='tem',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TEM (%)'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='term_days',
            field=models.IntegerField(default=0, verbose_name='Plazo (Días)'),
        ),
        migrations.AlterField(
            model_name='liqsavingsaccount',
            name='document',
            field=models.CharField(blank=True, max_length=20, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='liqsavingsaccount',
            name='last_movement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Último Movimiento'),
        ),
        migrations.AlterField(
            model_name='liqsavingsaccount',
            name='segment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Original'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='document',
            field=models.CharField(blank=True, max_length=20, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='TEA (%)'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='residual_term',
            field=models.IntegerField(default=0, verbose_name='Plazo Residual'),
        ),
    ]
