# Generated by Django 5.2.7 on 2026-05-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0026_liqsavingsaccount_cancellation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqsavingsaccount',
            name='customer_type',
            field=models.CharField(default='NATURAL', max_length=20, verbose_name='Tipo Cliente'),
        ),
        migrations.AddField(
            model_name='liqtermdeposit',
            name='customer_type',
            field=models.CharField(default='NATURAL', max_length=20, verbose_name='Tipo Cliente'),
        ),
    ]
