# Generated by Django 5.2.7 on 2026-05-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0028_liqlarconfig_alter_liqaccountmapping_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='liqaccountmapping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqaccountplanmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqapproval',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqauditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqavailablefund',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqbalancedetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqbalanceupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqbreach',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqconcentrationreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqcontingencyaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqcontingencyactivation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqcontingencyplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqcontributor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqfundingline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqfundingupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqgapdetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqgapreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqinvestment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqinvestmentupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqlarconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqlarresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqlimit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqmonthlyindicator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqmonthlyposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqportfoliodetail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqsavingsaccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqsavingsupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqsbslimit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqstressresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqstressrun',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqstressscenario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqtermdeposit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqtermdepositupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liqtimeband',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LiqLiabilityUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('file_source', models.FileField(upload_to='liquidity/liabilities/', verbose_name='Archivo Fuente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VALIDATING', 'Validando'), ('SUCCESS', 'Cargado con éxito'), ('ERROR', 'Error'), ('APPROVED', 'Aprobado')], default='PENDING', max_length=20)),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga de Pasivos',
                'unique_together': {('period',)},
            },
        ),
        migrations.CreateModel(
            name='LiqLiabilityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Periodo')),
                ('agency', models.CharField(max_length=100, verbose_name='Agencia')),
                ('opening_agency', models.CharField(blank=True, max_length=100, verbose_name='A.G. Apertura')),
                ('customer_id', models.CharField(db_index=True, max_length=50, verbose_name='Socio')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Apellidos y Nombres')),
                ('customer_age', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('customer_gender', models.CharField(blank=True, max_length=10, verbose_name='Sexo')),
                ('customer_birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('opening_date', models.DateField(verbose_name='Fecha Apertura')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('account_number', models.CharField(max_length=50, verbose_name='Nro Cuenta')),
                ('product', models.CharField(max_length=100, verbose_name='Producto')),
                ('currency', models.CharField(db_index=True, max_length=10, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Saldo')),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TEA')),
                ('tem', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='TEM')),
                ('term_days', models.IntegerField(default=0, verbose_name='Plazo')),
                ('created_by_user_code', models.CharField(blank=True, max_length=50, verbose_name='Usuario Crea')),
                ('captador', models.CharField(blank=True, max_length=100, verbose_name='Captador')),
                ('cancellation_date', models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación')),
                ('liquidity_item', models.CharField(db_index=True, max_length=100, verbose_name='Rubro Liquidez')),
                ('funding_type', models.CharField(db_index=True, max_length=20, verbose_name='Tipo Captación')),
                ('cut_off_status', models.CharField(db_index=True, max_length=20, verbose_name='Estado Registro')),
                ('days_to_due', models.IntegerField(blank=True, null=True, verbose_name='Días al Vencimiento')),
                ('liquidity_band', models.CharField(db_index=True, max_length=20, verbose_name='Banda Liquidez')),
                ('is_observed', models.BooleanField(default=False, verbose_name='Observado')),
                ('observation_detail', models.TextField(blank=True, verbose_name='Detalle Observación')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='liquidity_risk.liqliabilityupload')),
            ],
            options={
                'verbose_name': 'Detalle de Pasivo',
                'indexes': [models.Index(fields=['period', 'funding_type'], name='liquidity_r_period_b949ef_idx'), models.Index(fields=['period', 'liquidity_band'], name='liquidity_r_period_aa8a92_idx')],
            },
        ),
    ]
