# Generated by Django 5.2.7 on 2026-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0029_alter_liqaccountmapping_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqliabilitydetail',
            name='segment',
            field=models.CharField(blank=True, default='PERSONA NATURAL', max_length=100, verbose_name='Segmento'),
        ),
    ]
