# Generated by Django 5.2.7 on 2026-05-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity_risk', '0030_liqliabilitydetail_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqlarresult',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='Usar para Brechas'),
        ),
    ]
