# Generated by Django 5.2.7 on 2026-05-13 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_organizationalunit_id_alter_parameter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='related_processes',
            field=models.ManyToManyField(blank=True, to='catalogs.process', verbose_name='Procesos Relacionados'),
        ),
        migrations.AddField(
            model_name='process',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='catalogs.organizationalunit', verbose_name='Unidad Organizacional'),
        ),
    ]
