# Generated by Django 5.2.7 on 2026-05-13 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_organizationalunit_id_alter_parameter_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='RUC / Tax ID')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Gerencia')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'Gerencias',
            },
        ),
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={'verbose_name': 'Área / Unidad', 'verbose_name_plural': 'Áreas / Unidades'},
        ),
        migrations.RemoveField(
            model_name='process',
            name='related_processes',
        ),
        migrations.AddField(
            model_name='process',
            name='classification',
            field=models.CharField(choices=[('STRATEGIC', 'Estratégico'), ('MISSIONAL', 'Misional'), ('SUPPORT', 'Apoyo')], default='MISSIONAL', max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='process',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='process',
            name='frequency',
            field=models.CharField(blank=True, help_text='Ej: Diario, Mensual', max_length=100, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='process',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Objetivo'),
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('UNDER_REVIEW', 'En Revisión')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Área / Departamento'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='process',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='catalogs.organizationalunit', verbose_name='Área Asociada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Actividad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='catalogs.subprocess')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='catalogs.management', verbose_name='Gerencia'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sede / Local')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='catalogs.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.AddField(
            model_name='management',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='catalogs.site', verbose_name='Sede'),
        ),
    ]
