# Generated by Django 6.0.5 on 2026-07-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_position_organizationalunit_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='catalogs.organizationalunit', verbose_name='Área / Departamento'),
        ),
    ]
