# Generated by Django 6.0.5 on 2026-07-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_position_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini AI'), ('google_drive', 'Google Drive'), ('google_calendar', 'Google Calendar')], max_length=50, unique=True, verbose_name='Proveedor')),
                ('api_key', models.CharField(blank=True, help_text='Ej: API Key de Gemini', max_length=255, null=True, verbose_name='Clave API (Simple)')),
                ('json_credentials', models.TextField(blank=True, help_text='Pega el contenido del credentials.json aquí', null=True, verbose_name='Credenciales JSON')),
                ('extra_config', models.CharField(blank=True, max_length=255, null=True, verbose_name='Configuración Extra (Ej: Folder ID)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Integración del Sistema',
                'verbose_name_plural': 'Integraciones del Sistema',
            },
        ),
    ]
