# Generated by Django 6.0.5 on 2026-07-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_systemintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemintegration',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI (ChatGPT)'), ('mistral', 'Mistral AI'), ('google_drive', 'Google Drive'), ('google_calendar', 'Google Calendar')], max_length=50, unique=True, verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='AIModulePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('op_risk', 'Riesgo Operacional'), ('credit_risk', 'Riesgo de Crédito'), ('strategic_risk', 'Riesgo Estratégico')], max_length=50, unique=True, verbose_name='Módulo')),
                ('model_name', models.CharField(default='gemini-flash-latest', help_text='Nombre exacto del modelo según la API del proveedor.', max_length=100, verbose_name='Modelo (Ej: gpt-4o, gemini-flash-latest)')),
                ('system_prompt', models.TextField(help_text='Instrucciones base (Rol) para la IA en este módulo.', verbose_name='Prompt del Sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('provider', models.ForeignKey(limit_choices_to={'provider__in': ['gemini', 'openai', 'mistral']}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.systemintegration', verbose_name='Proveedor de IA')),
            ],
            options={
                'verbose_name': 'Prompt de IA por Módulo',
                'verbose_name_plural': 'Prompts de IA por Módulo',
            },
        ),
    ]
