# Generated by Django 6.0.5 on 2026-07-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_alter_systemintegration_provider_aimoduleprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimoduleprompt',
            name='model_name',
            field=models.CharField(choices=[('gemini-flash-latest', 'Gemini Flash (Rápido)'), ('gemini-pro-latest', 'Gemini Pro (Avanzado)'), ('gpt-4o', 'GPT-4o (Avanzado)'), ('gpt-4o-mini', 'GPT-4o Mini (Rápido)'), ('mistral-large-latest', 'Mistral Large'), ('mistral-small-latest', 'Mistral Small')], default='gemini-flash-latest', help_text='Nombre exacto del modelo según la API del proveedor.', max_length=100, verbose_name='Modelo (Ej: gpt-4o, gemini-flash-latest)'),
        ),
    ]
