# Generated by Django 6.0.5 on 2026-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_alter_aimoduleprompt_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Riesgo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Notas')),
            ],
            options={
                'verbose_name': 'Catálogo de Riesgo',
                'verbose_name_plural': 'Catálogo de Riesgos',
            },
        ),
    ]
