# Generated by Django 6.0.5 on 2026-07-15 16:40

from django.db import migrations


def populate_standard_risks(apps, schema_editor):
    RiskCatalog = apps.get_model('catalogs', 'RiskCatalog')
    standard_risks = [
        "Robo de efectivo en caja",
        "Asalto a mano armada en agencia",
        "Fraude con tarjetas de crédito/débito",
        "Suplantación de identidad de clientes",
        "Apropiación ilícita por parte de empleados",
        "Manipulación de estados financieros",
        "Lavado de activos o financiamiento del terrorismo",
        "Caída del servidor principal (Core Bancario)",
        "Interrupción de conectividad o internet",
        "Ataque de ransomware / malware",
        "Fuga de información confidencial de clientes",
        "Errores de digitación en ingresos de datos",
        "Falla en la conciliación contable o bancaria",
        "Daño a infraestructura por desastres naturales",
        "Incendio o inundación en las instalaciones",
        "Vandalismo durante protestas sociales",
        "Fallas en el suministro eléctrico",
        "Incumplimiento de normativas regulatorias",
        "Demandas laborales por despido arbitrario",
        "Accidentes laborales dentro de la institución",
        "Fallas de proveedores críticos",
        "Inconsistencias en el proceso de otorgamiento de crédito",
        "Errores en el cálculo de intereses o comisiones"
    ]
    for risk_name in standard_risks:
        RiskCatalog.objects.get_or_create(name=risk_name)

class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0015_riskcatalog'),
    ]

    operations = [
        migrations.RunPython(populate_standard_risks),
    ]
