# Generated by Django 6.0.4 on 2026-04-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Riesgo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Detallada')),
                ('causes', models.TextField(blank=True, verbose_name='Causas')),
                ('consequences', models.TextField(blank=True, verbose_name='Consecuencias')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Riesgo')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.process', verbose_name='Proceso Afectado')),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.risktype', verbose_name='Tipo de Riesgo')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('inherent_probability', models.IntegerField(default=1, verbose_name='Probabilidad Inherente (1-5)')),
                ('inherent_impact', models.IntegerField(default=1, verbose_name='Impacto Inherente (1-5)')),
                ('inherent_score', models.IntegerField(default=1, editable=False, verbose_name='Puntaje Inherente')),
                ('residual_probability', models.IntegerField(default=1, verbose_name='Probabilidad Residual (1-5)')),
                ('residual_impact', models.IntegerField(default=1, verbose_name='Impacto Residual (1-5)')),
                ('residual_score', models.IntegerField(default=1, editable=False, verbose_name='Puntaje Residual')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios de Evaluación')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risks.risk')),
            ],
            options={
                'verbose_name': 'Evaluación de Riesgo',
                'verbose_name_plural': 'Evaluaciones de Riesgo',
            },
        ),
    ]
