# Generated by Django 5.2.7 on 2026-05-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_alter_risk_id_alter_riskassessment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='control_design',
            field=models.IntegerField(default=0, verbose_name='Diseño de Control (0-100%)'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='control_effectiveness',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Efectividad Total (%)'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='control_execution',
            field=models.IntegerField(default=0, verbose_name='Ejecución de Control (0-100%)'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='residual_score',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=5, verbose_name='Puntaje Residual'),
        ),
    ]
