# Generated by Django 5.2.7 on 2026-05-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_company_management_alter_organizationalunit_options_and_more'),
        ('risks', '0004_alter_risk_id_alter_riskassessment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nivel de Impacto')),
                ('value', models.IntegerField(verbose_name='Valor Numérico (1-5)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Criterio')),
            ],
            options={
                'verbose_name': 'Escala de Impacto',
                'verbose_name_plural': 'Escalas de Impacto',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ProbabilityScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nivel de Probabilidad')),
                ('value', models.IntegerField(verbose_name='Valor Numérico (1-5)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Criterio')),
            ],
            options={
                'verbose_name': 'Escala de Probabilidad',
                'verbose_name_plural': 'Escalas de Probabilidad',
                'ordering': ['value'],
            },
        ),
        migrations.RemoveField(
            model_name='risk',
            name='causes',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='consequences',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='control_design',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='control_effectiveness',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='control_execution',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='residual_impact',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='residual_probability',
        ),
        migrations.AddField(
            model_name='risk',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.activity', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.CharField(choices=[('OPERATIONAL', 'Operacional'), ('TECHNOLOGICAL', 'Tecnológico'), ('LEGAL', 'Legal'), ('FRAUD', 'Fraude'), ('CONTINUITY', 'Continuidad'), ('REPUTATIONAL', 'Reputacional')], default='OPERATIONAL', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='risk',
            name='criticallity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20, verbose_name='Criticidad Manual'),
        ),
        migrations.AddField(
            model_name='risk',
            name='subprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.subprocess', verbose_name='Subproceso'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='inherent_severity',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Severidad Inherente'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='mitigation_factor',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Factor de Mitigación (0-1)'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='residual_severity',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Severidad Residual'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.process', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.risktype', verbose_name='Tipo de Riesgo (Normativo)'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='inherent_score',
            field=models.IntegerField(default=0, editable=False, verbose_name='Puntaje Inherente'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='residual_score',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Puntaje Residual'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='inherent_impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inherent_assessments', to='risks.impactscale'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='inherent_probability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inherent_assessments', to='risks.probabilityscale'),
        ),
        migrations.CreateModel(
            name='RiskCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción de la Causa')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes_list', to='risks.risk')),
            ],
            options={
                'verbose_name': 'Causa de Riesgo',
                'verbose_name_plural': 'Causas de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='RiskConsequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequence_type', models.CharField(choices=[('FINANCIAL', 'Financiera'), ('LEGAL', 'Legal'), ('REPUTATIONAL', 'Reputacional'), ('OPERATIONAL', 'Operativa'), ('REGULATORY', 'Regulatoria')], max_length=20, verbose_name='Tipo de Consecuencia')),
                ('description', models.TextField(verbose_name='Descripción del Impacto')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequences_list', to='risks.risk')),
            ],
            options={
                'verbose_name': 'Consecuencia de Riesgo',
                'verbose_name_plural': 'Consecuencias de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='RiskMatrixConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_level', models.CharField(choices=[('GREEN', 'Verde (Bajo)'), ('YELLOW', 'Amarillo (Medio)'), ('ORANGE', 'Naranja (Alto)'), ('RED', 'Rojo (Crítico)')], max_length=20, verbose_name='Nivel de Severidad')),
                ('score', models.IntegerField(default=0, verbose_name='Puntaje Combinado')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.impactscale')),
                ('probability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.probabilityscale')),
            ],
            options={
                'verbose_name': 'Configuración de Matriz',
                'verbose_name_plural': 'Configuraciones de Matriz',
                'unique_together': {('probability', 'impact')},
            },
        ),
    ]
