# Generated by Django 6.0.4 on 2026-06-10 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Indicador (KPI)')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='Fórmula de Cálculo')),
                ('baseline', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Línea Base')),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Meta')),
                ('frequency', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=50, verbose_name='Frecuencia de Medición')),
                ('green_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Límite Verde (>=)')),
                ('yellow_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Límite Amarillo (>=)')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Objetivo Estratégico')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicPerspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Perspectiva')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
        ),
        migrations.CreateModel(
            name='KPIMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(verbose_name='Fecha de Medición')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Logrado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones / Desviaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='strategic_risk.kpi')),
            ],
        ),
        migrations.AddField(
            model_name='kpi',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='strategic_risk.strategicobjective'),
        ),
        migrations.AddField(
            model_name='strategicobjective',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='strategic_risk.strategicperspective'),
        ),
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('institution', models.CharField(default='COOPAC', max_length=200, verbose_name='Institución')),
                ('start_year', models.IntegerField(verbose_name='Año de Inicio')),
                ('horizon_years', models.IntegerField(choices=[(3, '3 Años'), (4, '4 Años'), (5, '5 Años')], default=3, verbose_name='Horizonte (Años)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('CLOSED', 'Cerrado'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Plan Estratégico',
                'verbose_name_plural': 'Planes Estratégicos',
            },
        ),
        migrations.AddField(
            model_name='strategicperspective',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perspectives', to='strategic_risk.strategicplan'),
        ),
        migrations.CreateModel(
            name='StrategicMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_type', models.CharField(choices=[('FODA', 'Matriz FODA'), ('EFI', 'Matriz EFI'), ('EFE', 'Matriz EFE'), ('MPC', 'Matriz de Perfil Competitivo')], max_length=10, verbose_name='Tipo de Matriz')),
                ('data', models.JSONField(default=dict, verbose_name='Datos de la Matriz')),
                ('conclusions', models.TextField(blank=True, null=True, verbose_name='Conclusiones')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrices', to='strategic_risk.strategicplan')),
            ],
        ),
        migrations.CreateModel(
            name='InternalDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operations_scope', models.TextField(blank=True, null=True, verbose_name='Ámbito de Operaciones')),
                ('credit_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis de Créditos (Interno)')),
                ('delinquency_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis de Mora')),
                ('deposit_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis de Depósitos (Interno)')),
                ('interest_rates', models.TextField(blank=True, null=True, verbose_name='Tasas de Interés por Tipo de Depósito')),
                ('strengths', models.TextField(blank=True, null=True, verbose_name='Fortalezas')),
                ('weaknesses', models.TextField(blank=True, null=True, verbose_name='Debilidades')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_diagnosis', to='strategic_risk.strategicplan')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_structure', models.TextField(blank=True, null=True, verbose_name='Estructura del Sistema Financiero')),
                ('credit_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis de Créditos')),
                ('deposit_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis de Depósitos')),
                ('trends_rates', models.TextField(blank=True, null=True, verbose_name='Tendencias y Tasas')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_environment', to='strategic_risk.strategicplan')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis Internacional')),
                ('national_analysis', models.TextField(blank=True, null=True, verbose_name='Análisis Nacional')),
                ('economic_vars', models.TextField(blank=True, null=True, verbose_name='Variables Económicas')),
                ('regulatory_vars', models.TextField(blank=True, null=True, verbose_name='Variables Regulatorias')),
                ('social_vars', models.TextField(blank=True, null=True, verbose_name='Variables Sociales')),
                ('technological_vars', models.TextField(blank=True, null=True, verbose_name='Variables Tecnológicas')),
                ('competitive_vars', models.TextField(blank=True, null=True, verbose_name='Variables Competitivas')),
                ('conclusions', models.TextField(blank=True, null=True, verbose_name='Conclusiones')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_environment', to='strategic_risk.strategicplan')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessModelCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versión')),
                ('customer_segments', models.TextField(blank=True, null=True, verbose_name='Segmentos de Clientes')),
                ('value_proposition', models.TextField(blank=True, null=True, verbose_name='Propuesta de Valor')),
                ('channels', models.TextField(blank=True, null=True, verbose_name='Canales')),
                ('customer_relationships', models.TextField(blank=True, null=True, verbose_name='Relaciones con Clientes')),
                ('revenue_streams', models.TextField(blank=True, null=True, verbose_name='Flujos de Ingreso')),
                ('key_resources', models.TextField(blank=True, null=True, verbose_name='Recursos Clave')),
                ('key_activities', models.TextField(blank=True, null=True, verbose_name='Actividades Clave')),
                ('key_partners', models.TextField(blank=True, null=True, verbose_name='Socios Clave')),
                ('cost_structure', models.TextField(blank=True, null=True, verbose_name='Estructura de Costos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas', to='strategic_risk.strategicplan')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto')),
                ('status', models.CharField(choices=[('Planificado', 'Planificado'), ('En Curso', 'En Curso'), ('Retrasado', 'Retrasado'), ('Completado', 'Completado')], max_length=50, verbose_name='Estado')),
                ('physical_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avance Físico (%)')),
                ('financial_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avance Financiero (%)')),
                ('risks', models.TextField(blank=True, null=True, verbose_name='Riesgos del Proyecto')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='strategic_risk.strategicobjective')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Encuesta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('target_audience', models.CharField(choices=[('Socios', 'Socios'), ('Clientes', 'Clientes'), ('Colaboradores', 'Colaboradores')], max_length=50, verbose_name='Público Objetivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='strategic_risk.strategicplan')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('Text', 'Texto Libre'), ('Rating', 'Calificación 1-5'), ('Boolean', 'Sí/No')], max_length=20, verbose_name='Tipo de Pregunta')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='strategic_risk.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Información del Encuestado (Opcional)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='strategic_risk.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Respuesta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategic_risk.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='strategic_risk.surveyresponse')),
            ],
        ),
    ]
