# Generated by Django 6.0.4 on 2026-06-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0002_alter_businessmodelcanvas_id_and_more'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpimeasurement',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='strategicobjective',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='strategicperspective',
            name='plan',
        ),
        migrations.AlterField(
            model_name='businessmodelcanvas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corporatephilosophy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externalenvironment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financialenvironment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internaldiagnosis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strategicmatrix',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strategicmatrix',
            name='matrix_type',
            field=models.CharField(choices=[('FODA', 'Matriz FODA'), ('EFI', 'Matriz EFI'), ('EFE', 'Matriz EFE'), ('MPC', 'Matriz de Perfil Competitivo'), ('METAS', 'Metas Planeadas')], max_length=10, verbose_name='Tipo de Matriz'),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strategicproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Indicador (KPI)')),
                ('formula', models.CharField(help_text='Fórmula matemática usando variables. Ej: (resultado_real / meta_programada) * 100', max_length=255)),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad (%, $, N°)')),
                ('frecuencia_medicion', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('linea_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('meta_final', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Indicador KPI',
            },
        ),
        migrations.CreateModel(
            name='MetaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo (Ej. Q1-2026, Enero-2026)')),
                ('meta_programada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Meta Programada')),
                ('resultado_real', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Resultado Real logrado')),
                ('porcentaje_cumplimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('semaforo', models.CharField(blank=True, help_text='Rojo, Amarillo, Verde', max_length=20, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_periodo', to='strategic_risk.indicador')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'unique_together': {('indicador', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código (Ej. OE-01)')),
                ('nombre', models.CharField(max_length=255, verbose_name='Objetivo Estratégico')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Objetivo Estratégico',
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='strategic_risk.objetivoestrategico'),
        ),
        migrations.AlterField(
            model_name='strategicproject',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='strategic_risk.objetivoestrategico'),
        ),
        migrations.CreateModel(
            name='Perspectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('FINANCIERA', 'Financiera'), ('SOCIOS_CLIENTES', 'Socios/Clientes'), ('PROCESOS', 'Procesos Internos'), ('APRENDIZAJE', 'Aprendizaje y Crecimiento')], max_length=50, verbose_name='Perspectiva')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_porcentual', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Perspectiva',
                'verbose_name_plural': 'Perspectivas',
                'unique_together': {('organization', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='perspectiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='strategic_risk.perspectiva'),
        ),
        migrations.DeleteModel(
            name='KPI',
        ),
        migrations.DeleteModel(
            name='KPIMeasurement',
        ),
        migrations.DeleteModel(
            name='StrategicPerspective',
        ),
        migrations.DeleteModel(
            name='StrategicObjective',
        ),
        migrations.AlterUniqueTogether(
            name='objetivoestrategico',
            unique_together={('organization', 'codigo')},
        ),
    ]
