# Generated by Django 6.0.4 on 2026-06-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0003_remove_kpimeasurement_kpi_and_more'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoIniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código del Proyecto')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('presupuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto Total ($)')),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_PROCESO', 'En Proceso'), ('RETRASADO', 'Retrasado'), ('COMPLETADO', 'Completado'), ('SUSPENDIDO', 'Suspendido')], default='PLANIFICADO', max_length=50, verbose_name='Estado')),
                ('porcentaje_avance_fisico', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avance Físico (%)')),
                ('porcentaje_avance_financiero', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avance Financiero (%)')),
                ('semaforo_ejecucion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Semáforo de Ejecución')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='strategic_risk.indicador')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Proyecto e Iniciativa',
                'verbose_name_plural': 'Proyectos e Iniciativas',
                'unique_together': {('organization', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='HitoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Hito/Entregable')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Programada de Entrega')),
                ('porcentaje_avance_programado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avance Programado (%)')),
                ('porcentaje_avance_real', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avance Real (%)')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación de Retraso')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='strategic_risk.proyectoiniciativa')),
            ],
            options={
                'verbose_name': 'Hito del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='EjecucionPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo (Ej. Mes/Trimestre)')),
                ('gasto_programado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gasto Programado ($)')),
                ('gasto_real', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gasto Real ($)')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificación de Desviación')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='strategic_risk.proyectoiniciativa')),
            ],
            options={
                'verbose_name': 'Ejecución Presupuestaria',
                'unique_together': {('proyecto', 'periodo')},
            },
        ),
        migrations.DeleteModel(
            name='StrategicProject',
        ),
    ]
