# Generated by Django 6.0.4 on 2026-06-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0004_proyectoiniciativa_hitoproyecto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='perspectiva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='perspectiva',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perspectivas', to='strategic_risk.strategicplan'),
        ),
        migrations.AlterField(
            model_name='perspectiva',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Perspectiva'),
        ),
        migrations.AlterUniqueTogether(
            name='perspectiva',
            unique_together={('plan', 'nombre')},
        ),
    ]
