# Generated by Django 6.0.4 on 2026-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0005_alter_perspectiva_unique_together_perspectiva_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoestrategico',
            name='area_responsable',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Área Responsable'),
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='tipo_objetivo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Objetivo'),
        ),
    ]
