# Generated by Django 6.0.4 on 2026-06-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0006_objetivoestrategico_area_responsable_and_more'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Área Responsable')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_responsables', to='strategic_risk.strategicplan')),
            ],
            options={
                'verbose_name': 'Área Responsable',
                'verbose_name_plural': 'Áreas Responsables',
                'unique_together': {('plan', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ResponsablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Responsable')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='strategic_risk.strategicplan')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'unique_together': {('plan', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Tipo de Objetivo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_objetivo', to='strategic_risk.strategicplan')),
            ],
            options={
                'verbose_name': 'Tipo de Objetivo',
                'verbose_name_plural': 'Tipos de Objetivo',
                'unique_together': {('plan', 'nombre')},
            },
        ),
    ]
