# Generated by Django 6.0.4 on 2026-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0007_arearesponsable_responsableplan_tipoobjetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicmatrix',
            name='matrix_type',
            field=models.CharField(choices=[('FODA', 'Matriz FODA'), ('EFI', 'Matriz EFI'), ('EFE', 'Matriz EFE'), ('MPC', 'Matriz de Perfil Competitivo'), ('METAS', 'Metas Planeadas'), ('CONCLUSIONES', 'Matriz de Conclusiones')], max_length=20, verbose_name='Tipo de Matriz'),
        ),
    ]
