# Generated by Django 6.0.4 on 2026-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0008_alter_strategicmatrix_matrix_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoestrategico',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso (%)'),
        ),
    ]
