# Generated by Django 6.0.4 on 2026-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0009_objetivoestrategico_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='medio_verificacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medio de Verificación'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso (%)'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable'),
        ),
    ]
