# Generated by Django 6.0.4 on 2026-06-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0010_indicador_fecha_fin_indicador_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='tipo_objetivo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo Objetivo'),
        ),
    ]
