# Generated by Django 6.0.4 on 2026-06-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0011_indicador_tipo_objetivo'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FO', 'Estrategias OFENSIVAS (F-O)'), ('DO', 'Estrategias REORIENTACIÓN (D-O)'), ('FA', 'Estrategias DEFENSIVAS (F-A)'), ('DA', 'Estrategias SUPERVIVENCIA (D-A)')], max_length=2, verbose_name='Tipo de Estrategia')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Estrategia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('perspectiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias', to='strategic_risk.perspectiva')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='strategic_risk.strategicplan')),
            ],
            options={
                'verbose_name': 'Estrategia',
                'verbose_name_plural': 'Estrategias',
            },
        ),
    ]
