# Generated by Django 6.0.4 on 2026-06-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0012_estrategia'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Presupuesto')),
                ('lider_proyecto', models.CharField(max_length=255, verbose_name='Líder de Proyecto')),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poas', to='strategic_risk.estrategia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Portafolio POA',
                'verbose_name_plural': 'Portafolios POA',
                'unique_together': {('organization', 'nombre_proyecto', 'anio')},
            },
        ),
    ]
