# Generated by Django 6.0.4 on 2026-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0013_portafoliopoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafoliopoa',
            name='lider_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Líder de Proyecto'),
        ),
    ]
