# Generated by Django 6.0.4 on 2026-06-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0014_alter_portafoliopoa_lider_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias', to='strategic_risk.objetivoestrategico'),
        ),
    ]
