# Generated by Django 6.0.4 on 2026-06-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0015_estrategia_objetivo'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='No.')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Actividad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha final')),
                ('duracion', models.IntegerField(verbose_name='Duración (días)')),
                ('predecesora', models.CharField(blank=True, max_length=50, null=True, verbose_name='Predecesora')),
                ('responsable', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('medio_verificacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medio de Verificación')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Costo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='strategic_risk.portafoliopoa')),
            ],
            options={
                'verbose_name': 'Actividad POA',
                'verbose_name_plural': 'Actividades POA',
                'ordering': ['numero'],
            },
        ),
    ]
