# Generated by Django 6.0.4 on 2026-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_risk', '0016_actividadpoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafoliopoa',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso (%)'),
        ),
    ]
