from django.urls import path
from . import views

app_name = 'financial_planning'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('balance-comprobacion/', views.trial_balance_viewer_no_id, name='trial_balance_viewer_no_id'),
    path('plan/nuevo/', views.plan_wizard_new, name='plan_wizard_new'),
    path('plan/<int:plan_id>/eliminar/', views.delete_plan, name='delete_plan'),
    path('plan/<int:plan_id>/wizard/', views.budget_wizard_new, name='plan_wizard'),
    path('plan/<int:plan_id>/balance/', views.trial_balance_viewer_no_id, name='trial_balance_viewer'),
    path('budget-wizard/new/', views.budget_wizard_new, name='budget_wizard_new'),
    path('api/api_historical_portfolio_data/', views.api_historical_portfolio_data, name='api_historical_portfolio_data'),
    path('api/api_available_portfolio_dates/', views.api_available_portfolio_dates, name='api_available_portfolio_dates'),
    path('api/api_historical_passive_data/', views.api_historical_passive_data, name='api_historical_passive_data'),
    path('api/api_available_passive_dates/', views.api_available_passive_dates, name='api_available_passive_dates'),
    path('api/api_available_historical_dates/', views.api_available_historical_dates, name='api_available_historical_dates'),
    path('api/api_trial_balance_data/', views.api_trial_balance_data, name='api_trial_balance_data'),
    path('plan/<int:plan_id>/api/api_get_trend_data/', views.api_get_trend_data, name='api_get_trend_data'),
    path('plan/<int:plan_id>/api/manage_assumptions/', views.manage_assumptions, name='manage_assumptions'),
    path('plan/<int:plan_id>/api/api_get_assumptions_product/', views.api_get_assumptions_product, name='api_get_assumptions_product'),
    path('plan/<int:plan_id>/api/api_save_assumptions_product/', views.api_save_assumptions_product, name='api_save_assumptions_product'),
    path('plan/<int:plan_id>/api/api_save_step_periods/', views.api_save_step_periods, name='api_save_step_periods'),
    path('plan/<int:plan_id>/api/api_run_montecarlo/', views.api_run_montecarlo, name='api_run_montecarlo'),
    path('plan/<int:plan_id>/api/save_institutional_assumptions/', views.save_institutional_assumptions, name='save_institutional_assumptions'),
    path('plan/<int:plan_id>/api/api_unlock_step6/', views.api_unlock_step6, name='api_unlock_step6'),
    path('plan/<int:plan_id>/api/api_save_trend_scenarios/', views.api_save_trend_scenarios, name='api_save_trend_scenarios'),
    path('plan/<int:plan_id>/api/toggle_step_lock/', views.toggle_step_lock, name='toggle_step_lock'),
    path('plan/<int:plan_id>/api/ml_trend_projection/', views.ml_trend_projection, name='ml_trend_projection'),
    path('plan/<int:plan_id>/api/ml_montecarlo_projection/', views.ml_montecarlo_projection, name='ml_montecarlo_projection'),
    path('plan/<int:plan_id>/api/api_lock_step6/', views.api_lock_step6, name='api_lock_step6'),
    path('plan/<int:plan_id>/api/save_scenario_fragment/', views.save_scenario_fragment, name='save_scenario_fragment'),
    path('plan/<int:plan_id>/api/projected_results/', views.projected_results, name='projected_results'),
    path('plan/<int:plan_id>/api/api_sync_budget_trends/', views.api_sync_budget_trends, name='api_sync_budget_trends'),
    path('plan/<int:plan_id>/api/api_get_budget_data/', views.api_get_budget_data, name='api_get_budget_data'),
    path('plan/<int:plan_id>/api/api_save_budget_version/', views.api_save_budget_version, name='api_save_budget_version'),
    path('plan/<int:plan_id>/api/api_approve_budget_version/', views.api_approve_budget_version, name='api_approve_budget_version'),
    path('plan/<int:plan_id>/api/api_copy_base_year_budget/', views.api_copy_base_year_budget, name='api_copy_base_year_budget'),
    path('api/assign_trial_balance_to_plan/', views.assign_trial_balance_to_plan, name='assign_trial_balance_to_plan'),
    path('plan/<int:plan_id>/export_er_proyectado/', views.export_er_proyectado, name='export_er_proyectado'),
    path('plan/<int:plan_id>/export_bg_proyectado/', views.export_bg_proyectado, name='export_bg_proyectado'),
    path('plan/<int:plan_id>/api/api_get_er_historico/', views.api_get_er_historico, name='api_get_er_historico'),
    path('plan/<int:plan_id>/api/api_seed_budget_items/', views.api_seed_budget_items, name='api_seed_budget_items'),
    path('plan/<int:plan_id>/api/api_get_historical_account_monthly/', views.api_get_historical_account_monthly, name='api_get_historical_account_monthly'),
    path('plan/<int:plan_id>/api/api_get_projected_balance_data/', views.api_get_projected_balance_data, name='api_get_projected_balance_data'),
    path('plan/<int:plan_id>/api/toggle_fixed_bg_account/', views.api_toggle_fixed_bg_account, name='api_toggle_fixed_bg_account'),
    path('plan/<int:plan_id>/api/clear_other_trends/', views.api_clear_other_trends, name='api_clear_other_trends'),
    path('plan/<int:plan_id>/api/save_bg_adjustment/', views.api_save_bg_adjustment, name='api_save_bg_adjustment'),
    path('plan/<int:plan_id>/api/save_bg_snapshot/', views.api_save_bg_snapshot, name='api_save_bg_snapshot'),
    path('plan/<int:plan_id>/api/modify_bg_snapshot/', views.api_modify_bg_snapshot, name='api_modify_bg_snapshot'),
    path('plan/<int:plan_id>/api/apply_other_trends/', views.api_apply_other_trends, name='api_apply_other_trends'),
    path('plan/<int:plan_id>/api/sync_core_trends_bg/', views.api_sync_core_trends_bg, name='api_sync_core_trends_bg'),
    path('plan/<int:plan_id>/api/api_get_cash_flow_data/', views.api_get_cash_flow_data, name='api_get_cash_flow_data'),
    path('plan/<int:plan_id>/api/save_cf_adjustment/', views.api_save_cf_adjustment, name='api_save_cf_adjustment'),
]
