# Generated by Django 6.0.4 on 2026-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('load_date', models.DateTimeField(auto_now_add=True)),
                ('cut_off_dates', models.TextField(blank=True, help_text='Lista de fechas de corte identificadas en la carga', null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-load_date'],
            },
        ),
    ]
