# Generated by Django 5.2.7 on 2026-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkloadlog',
            name='load_type',
            field=models.CharField(choices=[('CREDIT', 'Cartera de Créditos'), ('LIABILITY', 'Pasivos / Depósitos')], default='CREDIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkloadlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
