# Generated by Django 6.0.4 on 2026-05-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_bulkloadlog_load_type_alter_bulkloadlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkloadlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
