# Generated by Django 5.2.7 on 2026-05-23 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_alter_bulkloadlog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkloadlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bulkloadlog',
            name='load_type',
            field=models.CharField(choices=[('CREDIT', 'Cartera de Créditos'), ('LIABILITY', 'Pasivos / Depósitos'), ('SOCIO', 'Base de Socios')], default='CREDIT', max_length=20),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('canton', models.CharField(blank=True, max_length=100, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='utilities.bulkloadlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
