# Generated by Django 5.2.7 on 2026-05-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_alter_bulkloadlog_id_alter_bulkloadlog_load_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='canton',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='parroquia',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='tipo_identificacion',
        ),
        migrations.AddField(
            model_name='socio',
            name='aportes',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='SALDO DE APORTACIONES', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='codoficina',
            field=models.CharField(blank=True, help_text='CODIGO DE OFICINA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='condsocio',
            field=models.CharField(blank=True, help_text='CONDICIÓN DE SOCIO HABIL O INHABIL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='correo',
            field=models.EmailField(blank=True, help_text='CORREO', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='corte',
            field=models.DateField(blank=True, help_text='FECHA DE CORTE', null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='fingreso',
            field=models.DateField(blank=True, help_text='FECHA DE INGRESO', null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='ncl',
            field=models.CharField(blank=True, help_text='APELLIDOS Y NOMBRES O RAZÓN SOCIAL', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='nid',
            field=models.CharField(blank=True, help_text='NÚMERO DE DOCUMENTOS DE IDENTIDAD DNI O RUC', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='oficina',
            field=models.CharField(blank=True, help_text='NOMBRE DE OFICINA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='tid',
            field=models.IntegerField(blank=True, help_text='TIPO DE SOCIO, DONDE 1 ES PERSONA NATURAL Y 2 ES PERSONA JURIDICA', null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='direccion',
            field=models.TextField(blank=True, help_text='DIRECCIÓN DE DOMICILIO', null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, help_text='CELULAR', max_length=50, null=True),
        ),
    ]
