# Generated by Django 6.0.4 on 2026-05-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_remove_socio_agencia_remove_socio_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='csocio',
            field=models.CharField(blank=True, help_text='CÓDIGO DE SOCIO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bulkloadlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
