# Generated by Django 6.0.5 on 2026-07-14 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_socio_csocio_alter_bulkloadlog_id_alter_socio_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiqAccountPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del modelo de plan de cuentas (ej. ESTANDAR)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiqAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(help_text='Código contable', max_length=50)),
                ('account_name', models.CharField(help_text='Nombre de la cuenta', max_length=255)),
                ('liquidity_category', models.CharField(help_text='Categoría de liquidez asignada (ej. Activo Líquido, Pasivo Volátil)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='utilities.liqaccountplanmodel')),
            ],
            options={
                'unique_together': {('plan_model', 'account_code')},
            },
        ),
    ]
