# Generated by Django 6.0.5 on 2026-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_liqaccountplanmodel_liqaccountmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqaccountmapping',
            name='account_type',
            field=models.CharField(choices=[('ACT', 'Activo'), ('PAS', 'Pasivo'), ('PAT', 'Patrimonio'), ('ING', 'Ingreso'), ('GAS', 'Gasto'), ('OTR', 'Otro')], default='OTR', max_length=3),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='data_source',
            field=models.CharField(choices=[('BALANCE', 'Balance General (Contabilidad)'), ('CREDIT_RISK', 'Módulo Riesgo Crediticio'), ('MANUAL', 'Ingreso Manual'), ('CORE', 'Core Bancario / Otras Tablas')], default='BALANCE', max_length=20),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='distribution_rule',
            field=models.CharField(choices=[('SCHEDULE', 'Por Cronograma'), ('HISTORICAL', 'Distribución Histórica'), ('CONTRACTUAL', 'Vencimiento Contractual'), ('IMMEDIATE', 'Disponibilidad Inmediata'), ('OTHER', 'Otros')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='liqaccountmapping',
            name='liquidity_item',
            field=models.CharField(blank=True, help_text='Rubro Liquidez', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='liqaccountmapping',
            name='liquidity_category',
            field=models.CharField(blank=True, help_text='Categoría de liquidez asignada (ej. Activo Líquido, Pasivo Volátil)', max_length=100, null=True),
        ),
    ]
