# Generated by Django 6.0.4 on 2026-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_alter_bulkloadlog_id_alter_socio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkloadlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
