# Generated by Django 6.0.5 on 2026-07-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_liqaccountmapping_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('is_scheduled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
