# Generated by Django 6.0.5 on 2026-07-13 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_risk', '0018_carteracreditocarga_asesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverridingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('original_classification', models.CharField(max_length=50, verbose_name='Clasificación Original')),
                ('new_classification', models.CharField(max_length=50, verbose_name='Nueva Clasificación')),
                ('justification', models.TextField(verbose_name='Sustento Técnico')),
                ('cut_off_date', models.DateField(verbose_name='Fecha de Corte de Aplicación')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overridings', to='credit_risk.creditoperation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste por Excepción (Overriding)',
                'verbose_name_plural': 'Ajustes por Excepción (Overriding)',
            },
        ),
        migrations.CreateModel(
            name='TransitionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Desde Fecha')),
                ('to_date', models.DateField(verbose_name='Hasta Fecha')),
                ('from_category', models.CharField(max_length=50, verbose_name='Categoría Origen')),
                ('to_category', models.CharField(max_length=50, verbose_name='Categoría Destino')),
                ('probability', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Probabilidad Transición (%)')),
            ],
            options={
                'verbose_name': 'Matriz de Transición',
                'verbose_name_plural': 'Matrices de Transición',
                'unique_together': {('from_date', 'to_date', 'from_category', 'to_category')},
            },
        ),
        migrations.CreateModel(
            name='VintageCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_month', models.DateField(db_index=True, verbose_name='Mes de Cosecha')),
                ('cut_off_date', models.DateField(db_index=True, verbose_name='Fecha de Corte de Medición')),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Desembolsado Total')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Saldo Vigente')),
                ('past_due_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Saldo Vencido (>30 días)')),
                ('npl_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Ratio de Mora (%)')),
            ],
            options={
                'verbose_name': 'Cohorte de Cosecha (Vintage)',
                'verbose_name_plural': 'Cohortes de Cosecha (Vintage)',
                'unique_together': {('disbursement_month', 'cut_off_date')},
            },
        ),
        migrations.CreateModel(
            name='RiskClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_off_date', models.DateField(db_index=True, verbose_name='Fecha de Corte')),
                ('bucket', models.CharField(max_length=50, verbose_name='Bucket de Mora')),
                ('days_past_due', models.IntegerField(default=0, verbose_name='Días de Mora')),
                ('sbs_classification', models.CharField(max_length=50, verbose_name='Clasificación SBS')),
                ('pd', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='PD (%)')),
                ('lgd', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='LGD (%)')),
                ('ead', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='EAD')),
                ('expected_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pérdida Esperada')),
                ('required_provision', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Provisión Requerida')),
                ('snapshot_data', models.JSONField(blank=True, default=dict, help_text='Datos estáticos al momento del cálculo (tasas vigentes, garantías)', verbose_name='Snapshot Variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_classifications', to='credit_risk.creditoperation')),
            ],
            options={
                'verbose_name': 'Clasificación Histórica de Riesgo',
                'verbose_name_plural': 'Clasificaciones Históricas de Riesgo',
                'unique_together': {('operation', 'cut_off_date')},
            },
        ),
    ]
