# Generated by Django 6.0.5 on 2026-07-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0018_carteracreditocarga_asesor'),
        ('modulo_riesgo_credito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100, verbose_name='Tipo de Alerta')),
                ('description', models.TextField(verbose_name='Descripción de la Alerta')),
                ('date_detected', models.DateField(auto_now_add=True, verbose_name='Fecha Detectada')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('severity', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=20, verbose_name='Severidad')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_alerts', to='credit_risk.creditoperation')),
            ],
            options={
                'verbose_name': 'Alerta Temprana Activa',
                'verbose_name_plural': 'Alertas Tempranas Activas',
            },
        ),
    ]
