# Generated by Django 6.0.4 on 2026-05-08 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Requisito legal, regulatorio o interno')),
                ('source', models.CharField(choices=[('SBS', 'SBS - Banca y Seguros'), ('SUNAT', 'SUNAT - Tributario'), ('LABORAL', 'Normativa Laboral'), ('PRIVACIDAD', 'Protección de Datos'), ('INTERNA', 'Políticas Internas'), ('OTROS', 'Otras Obligaciones')], default='SBS', max_length=20, verbose_name='Fuente')),
                ('responsible_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organizationalunit', verbose_name='Área responsable')),
            ],
            options={
                'verbose_name': 'Obligación de Cumplimiento',
                'verbose_name_plural': 'Obligaciones de Cumplimiento',
            },
        ),
        migrations.CreateModel(
            name='ComplianceRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inherent_probability', models.IntegerField(default=3, verbose_name='Probabilidad Inherente (1-5)')),
                ('inherent_impact', models.IntegerField(default=3, verbose_name='Impacto Inherente (1-5)')),
                ('existing_controls', models.TextField(blank=True, verbose_name='Controles existentes')),
                ('residual_probability', models.IntegerField(default=2, verbose_name='Probabilidad Residual (1-5)')),
                ('residual_impact', models.IntegerField(default=2, verbose_name='Impacto Residual (1-5)')),
                ('indicator', models.TextField(blank=True, verbose_name='Indicador de cumplimiento')),
                ('monitoring_frequency', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=20, verbose_name='Frecuencia de monitoreo')),
                ('evaluation_period', models.CharField(default='2026', help_text='Ej: 2026', max_length=100, verbose_name='Periodo de evaluación')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='compliance_risk.compliancerequirement', verbose_name='Requisito')),
            ],
            options={
                'verbose_name': 'Riesgo de Cumplimiento',
                'verbose_name_plural': 'Matriz de Riesgos de Cumplimiento',
            },
        ),
        migrations.CreateModel(
            name='ComplianceFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción del Hallazgo')),
                ('state', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateField(verbose_name='Fecha Límite de Subsanación')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='compliance_risk.compliancerisk', verbose_name='Riesgo Asociado')),
            ],
            options={
                'verbose_name': 'Hallazgo de Cumplimiento',
                'verbose_name_plural': 'Hallazgos de Cumplimiento',
            },
        ),
    ]
