# Generated by Django 6.0.4 on 2026-05-08 14:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('compliance_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 8, 14, 18, 32, 757655, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='potential_sanction',
            field=models.TextField(blank=True, verbose_name='Sanción Potencial (Multas/Medidas)'),
        ),
        migrations.AlterField(
            model_name='compliancerequirement',
            name='description',
            field=models.TextField(verbose_name='Descripción del Requisito'),
        ),
        migrations.AlterField(
            model_name='compliancerequirement',
            name='responsible_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organizationalunit', verbose_name='Área Responsable'),
        ),
        migrations.AlterField(
            model_name='compliancerequirement',
            name='source',
            field=models.CharField(choices=[('SBS', 'SBS - Superintendencia de Banca y Seguros'), ('SUNAT', 'SUNAT - Administración Tributaria'), ('UIF', 'UIF-Perú - Inteligencia Financiera'), ('INDECOPI', 'INDECOPI - Protección al Consumidor'), ('SUNAFIL', 'SUNAFIL - Fiscalización Laboral'), ('PRIVACIDAD', 'Protección de Datos Personales'), ('INTERNA', 'Políticas Internas / Otros')], max_length=20, verbose_name='Fuente / Ente Sancionador'),
        ),
    ]
