# Generated by Django 6.0.4 on 2026-05-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_risk', '0003_alter_compliancefinding_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancefinding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compliancerequirement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compliancerisk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
