# Generated by Django 6.0.4 on 2026-04-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaftCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True, verbose_name='ID Socio')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', max_length=10, verbose_name='Nivel de Riesgo')),
                ('last_review', models.DateField(auto_now=True, verbose_name='Última Revisión')),
                ('is_pep', models.BooleanField(default=False, verbose_name='Es PEP')),
            ],
            options={
                'verbose_name': 'Perfil PLAFT de Cliente',
                'verbose_name_plural': 'Perfiles PLAFT de Clientes',
            },
        ),
        migrations.CreateModel(
            name='PlaftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100, verbose_name='Tipo de Alerta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date_triggered', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Activación')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ANALYZING', 'En Análisis'), ('DISCARDED', 'Descartada'), ('ROS', 'Reportada (ROS)')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaft_risk.plaftcustomerprofile', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Alerta PLAFT',
                'verbose_name_plural': 'Alertas PLAFT',
            },
        ),
    ]
