# Generated by Django 5.2.7 on 2026-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaft_risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaftalert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plaftcustomerprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
