# Generated by Django 6.0.4 on 2026-05-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaft_risk', '0002_alter_plaftalert_id_alter_plaftcustomerprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaftalert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plaftcustomerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
