# Generated by Django 5.2.7 on 2026-06-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_financial_planning',
            field=models.BooleanField(default=True, help_text='Permite al usuario visualizar y acceder al módulo de Planeamiento Financiero.', verbose_name='Acceso: Planeamiento Financiero'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_integral_risk',
            field=models.BooleanField(default=True, help_text='Permite al usuario visualizar y acceder al módulo de Gestión Integral de Riesgos.', verbose_name='Acceso: Gestión Integral de Riesgos'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_strategic_planning',
            field=models.BooleanField(default=True, help_text='Permite al usuario visualizar y acceder al módulo de Planeamiento Estratégico.', verbose_name='Acceso: Planeamiento Estratégico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
