# Generated by Django 6.0.5 on 2026-07-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Área / Departamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo'),
        ),
    ]
