# Generated by Django 6.0.5 on 2026-07-15 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_position_organizationalunit_is_active'),
        ('users', '0004_user_department_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organizationalunit', verbose_name='Área / Departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.position', verbose_name='Cargo'),
        ),
    ]
