# Generated by Django 5.2.7 on 2026-06-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_can_access_financial_planning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Perfil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='Permisos')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_financial_planning',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_integral_risk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_strategic_planning',
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_financial_planning_flag',
            field=models.BooleanField(default=True, verbose_name='Acceso (Legacy): Planeamiento Financiero'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_integral_risk_flag',
            field=models.BooleanField(default=True, verbose_name='Acceso (Legacy): Gestión Integral de Riesgos'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_strategic_planning_flag',
            field=models.BooleanField(default=True, verbose_name='Acceso (Legacy): Planeamiento Estratégico'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role', verbose_name='Perfil de Usuario'),
        ),
    ]
