# Generated by Django 5.2.7 on 2026-06-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden_modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Módulos Ocultos'),
        ),
    ]
