# Generated by Django 6.0.5 on 2026-07-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Indicador')),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor Límite')),
                ('is_percentage', models.BooleanField(default=True, verbose_name='Es Porcentaje?')),
            ],
            options={
                'verbose_name': 'Límite de Mercado',
                'verbose_name_plural': 'Límites de Mercado',
            },
        ),
        migrations.CreateModel(
            name='MarketPositionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(verbose_name='Fecha de corte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
            ],
            options={
                'verbose_name': 'Carga de Posiciones',
                'verbose_name_plural': 'Cargas de Posiciones',
                'ordering': ['-period_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Escenario')),
                ('scenario_type', models.CharField(choices=[('SENS', 'Sensibilidad'), ('STRESS', 'Estrés')], default='SENS', max_length=15, verbose_name='Tipo')),
                ('rate_shock_bps', models.IntegerField(default=0, help_text='Ej: 100 para +1%, -50 para -0.5%', verbose_name='Shock Tasas (bps)')),
                ('fx_shock_percent', models.DecimalField(decimal_places=4, default=0, help_text='Ej: 5 para depreciación de 5%', max_digits=10, verbose_name='Shock T.C. (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Escenario de Mercado',
                'verbose_name_plural': 'Escenarios de Mercado',
            },
        ),
        migrations.CreateModel(
            name='MarketTimeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: 0-30 días, 31-90 días, etc.', max_length=50, verbose_name='Nombre de la banda')),
                ('order', models.IntegerField(default=1, verbose_name='Orden de visualización')),
                ('days_start', models.IntegerField(blank=True, null=True, verbose_name='Límite inferior en días')),
                ('days_end', models.IntegerField(blank=True, null=True, verbose_name='Límite superior en días')),
            ],
            options={
                'verbose_name': 'Banda Temporal',
                'verbose_name_plural': 'Bandas Temporales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarketPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('INVESTMENT', 'Inversión')], max_length=20, verbose_name='Tipo')),
                ('account_code', models.CharField(max_length=50, verbose_name='Código de Cuenta')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('currency', models.CharField(choices=[('MN', 'Moneda Nacional'), ('ME', 'Moneda Extranjera')], default='MN', max_length=10, verbose_name='Moneda')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo')),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Tasa Efectiva Anual (Ej: 12.5 para 12.5%)', max_digits=10, verbose_name='TEA (%)')),
                ('repricing_date', models.DateField(blank=True, null=True, verbose_name='Fecha Reprecio/Vcto.')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='market_risk.marketpositionupload')),
                ('time_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='market_risk.markettimeband')),
            ],
            options={
                'verbose_name': 'Posición de Mercado',
                'verbose_name_plural': 'Posiciones de Mercado',
                'indexes': [models.Index(fields=['upload', 'position_type'], name='market_risk_upload__585c6a_idx')],
            },
        ),
    ]
