# Generated by Django 6.0.4 on 2026-04-28 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Control')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('control_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('DETECTIVE', 'Detectivo'), ('CORRECTIVE', 'Correctivo')], max_length=20, verbose_name='Tipo de Control')),
                ('frequency', models.CharField(help_text='Ej: Diario, Mensual, Anual', max_length=100, verbose_name='Frecuencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Control')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='risks.risk')),
            ],
            options={
                'verbose_name': 'Control de Riesgo',
                'verbose_name_plural': 'Controles de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='ControlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Prueba')),
                ('effectiveness_score', models.IntegerField(default=100, verbose_name='Nivel de Efectividad (1-100%)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='controls.riskcontrol')),
            ],
            options={
                'verbose_name': 'Prueba de Control',
                'verbose_name_plural': 'Pruebas de Control',
            },
        ),
    ]
