# Generated by Django 5.2.7 on 2026-05-13 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_alter_controltest_id_alter_riskcontrol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcontrol',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='controls/evidence/', verbose_name='Evidencia'),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='controltest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskcontrol',
            name='frequency',
            field=models.CharField(help_text='Ej: Diario, Mensual, Anual', max_length=100, verbose_name='Periodicidad'),
        ),
        migrations.AlterField(
            model_name='riskcontrol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
