# Generated by Django 6.0.5 on 2026-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_riskcontrol_created_at_riskcontrol_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskcontrol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
