# Generated by Django 6.0.4 on 2026-04-28 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=20, unique=True, verbose_name='Documento/DNI')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre/Razón Social')),
                ('segment', models.CharField(max_length=100, verbose_name='Segmento')),
                ('economic_activity', models.CharField(max_length=255, verbose_name='Actividad Económica')),
                ('zone', models.CharField(max_length=100, verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Cliente / Socio',
                'verbose_name_plural': 'Clientes / Socios',
            },
        ),
        migrations.CreateModel(
            name='CreditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Operación')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (%)')),
                ('term', models.IntegerField(verbose_name='Plazo (meses)')),
                ('guarantee_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Garantía')),
                ('guarantee_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Garantía')),
                ('bucket', models.CharField(blank=True, max_length=50, verbose_name='Bucket / Tramo de Mora')),
                ('days_past_due', models.IntegerField(default=0, verbose_name='Días de Mora')),
                ('sbs_classification', models.CharField(blank=True, max_length=50, verbose_name='Clasificación SBS')),
                ('provision', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Provisión Mínima')),
                ('is_refinanced', models.BooleanField(default=False, verbose_name='¿Refinanciado?')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.product', verbose_name='Producto')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='credit_risk.customer')),
            ],
            options={
                'verbose_name': 'Operación Crediticia',
                'verbose_name_plural': 'Operaciones Crediticias',
            },
        ),
        migrations.CreateModel(
            name='CreditRiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Probabilidad de Incumplimiento (PD %)')),
                ('ead', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Exposición (EAD)')),
                ('lgd', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Pérdida Dado el Incumplimiento (LGD %)')),
                ('expected_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pérdida Esperada (EL)')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='credit_risk.creditoperation')),
            ],
            options={
                'verbose_name': 'Métrica de Riesgo de Crédito',
                'verbose_name_plural': 'Métricas de Riesgo de Crédito',
            },
        ),
    ]
