# Generated by Django 6.0.4 on 2026-04-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoperation',
            name='load_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Corte / Carga'),
        ),
    ]
