# Generated by Django 6.0.4 on 2026-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0002_creditoperation_load_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoperation',
            name='advisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asesor de Crédito'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='agency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Agencia/Oficina'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='currency',
            field=models.CharField(default='PEN', max_length=3, verbose_name='Moneda (PEN/USD)'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='disbursement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Desembolso'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Desembolsado'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='customer',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Socio'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Género (M/F)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
    ]
