# Generated by Django 6.0.4 on 2026-04-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('credit_risk', '0003_creditoperation_advisor_creditoperation_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoperation',
            name='advisor_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de Analista / Solicitud'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='agreement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Convenio'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='credit_type',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de Crédito'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='current_portfolio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cartera Vigente'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='established_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Provisión Constituida'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='generic_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Provisión Genérica'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='interest_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Interés por Cobrar'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='interest_suspended',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Interés Suspenso'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='last_movement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última Fecha de Movimiento'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='past_due_portfolio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cartera Vencida'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre Producto (Texto)'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='refinanced_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Refinanciado Vigente'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='refinanced_past_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Refinanciado Vencida'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='required_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Provisión Requerida'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='restructured_current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Reprogramación Vigente'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='restructured_past_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Reprogramación Vencida'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='specific_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Provisión Específica'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='operation_code',
            field=models.CharField(max_length=50, verbose_name='Código de Operación'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Provisión Mínima (Legacy)'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa (%)'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='term',
            field=models.IntegerField(default=0, verbose_name='Plazo (meses)'),
        ),
        migrations.AddConstraint(
            model_name='creditoperation',
            constraint=models.UniqueConstraint(fields=('operation_code', 'load_date'), name='unique_op_per_cutoff'),
        ),
    ]
