# Generated by Django 6.0.4 on 2026-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0004_creditoperation_advisor_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditriskmetrics',
            name='lgd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Pérdida Dado el Incumplimiento (LGD %)'),
        ),
        migrations.AlterField(
            model_name='creditriskmetrics',
            name='pd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='Probabilidad de Incumplimiento (PD %)'),
        ),
    ]
