# Generated by Django 6.0.4 on 2026-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0005_alter_creditriskmetrics_lgd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoperation',
            name='advisor',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Asesor de Crédito'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='agency',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Agencia/Oficina'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='credit_type',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Tipo de Crédito'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='load_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Corte / Carga'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='product_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Nombre Producto (Texto)'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='sbs_classification',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Clasificación SBS'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Segmento'),
        ),
    ]
