# Generated by Django 6.0.4 on 2026-04-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0006_alter_creditoperation_advisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoperation',
            name='advisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asesor de Crédito'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='credit_type',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tipo de Crédito'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='days_past_due',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Días de Mora'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(max_length=100, verbose_name='Segmento'),
        ),
    ]
