# Generated by Django 6.0.4 on 2026-05-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0007_alter_creditoperation_advisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRiskPeriodParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateField(unique=True, verbose_name='Fecha de Corte')),
                ('monto_mitigador', models.DecimalField(decimal_places=2, default=50000000.0, max_digits=18, verbose_name='Patrimonio Efectivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Notas')),
            ],
            options={
                'verbose_name': 'Parámetro de Riesgo por Periodo',
                'verbose_name_plural': 'Parámetros de Riesgo por Periodo',
                'ordering': ['-load_date'],
            },
        ),
    ]
