# Generated by Django 5.2.7 on 2026-05-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0008_creditriskperiodparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditriskperiodparameter',
            name='patrimonio_efectivo',
            field=models.DecimalField(decimal_places=2, default=500000000.0, max_digits=18, verbose_name='Patrimonio Efectivo'),
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditriskmetrics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditriskperiodparameter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditriskperiodparameter',
            name='monto_mitigador',
            field=models.DecimalField(decimal_places=2, default=50000000.0, max_digits=18, verbose_name='Monto Mitigador (Calculado)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
