# Generated by Django 5.2.7 on 2026-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0009_creditriskperiodparameter_patrimonio_efectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoperation',
            name='maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='creditoperation',
            name='payment_periodicity',
            field=models.IntegerField(default=30, verbose_name='Periodicidad de Pago (Días)'),
        ),
    ]
