# Generated by Django 5.2.7 on 2026-05-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0010_creditoperation_maturity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoperation',
            name='judicial_portfolio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cartera Judicial'),
        ),
    ]
