# Generated by Django 5.2.7 on 2026-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_alter_activity_id_alter_company_id_and_more'),
        ('credit_risk', '0012_alter_creditoperation_id_alter_creditriskmetrics_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditoperation',
            name='unique_op_per_cutoff',
        ),
        migrations.AlterField(
            model_name='creditoperation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditriskmetrics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditriskperiodparameter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='creditoperation',
            constraint=models.UniqueConstraint(fields=('customer', 'operation_code', 'load_date'), name='unique_op_per_cutoff'),
        ),
    ]
