# Generated by Django 6.0.5 on 2026-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0014_carteracreditocarga_alter_creditoperation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteracreditocarga',
            name='adm_agen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adm-Agen'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='agencia_calc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Agencia (Calc)'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='clasif_calc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificación (Calc)'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='cod_asesor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cod Asesor'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='cosecha',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cosecha'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='id_compuesto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Compuesto'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='producto_agrupado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto Agrupado'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='prov_especifica',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='P. Especifica'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='prov_generica',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='P. Generica'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='rango_desemb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rango Desemb'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='rango_mora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rango Mora'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='saldo_calc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo (Calc)'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='saldo_mas_120d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo >120D'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='saldo_mas_30d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo >30D'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='saldo_mas_3d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo >3D'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='saldo_mas_60d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo >60D'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='saldo_mas_8d',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Saldo >8D'),
        ),
        migrations.AddField(
            model_name='carteracreditocarga',
            name='tem',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='TEM'),
        ),
    ]
