# Generated by Django 6.0.5 on 2026-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0015_carteracreditocarga_adm_agen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoperation',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Tasa (%)'),
        ),
    ]
