# Generated by Django 6.0.5 on 2026-07-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0017_remove_carteracreditocarga_act_economica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteracreditocarga',
            name='asesor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asesor'),
        ),
    ]
