# Generated by Django 6.0.5 on 2026-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0018_carteracreditocarga_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteracreditocarga',
            name='fecha_corte',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Corte'),
        ),
    ]
