# Generated by Django 6.0.4 on 2026-05-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0006_alter_activity_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('version_type', models.CharField(choices=[('OPTIMISTIC', 'Optimista'), ('NEUTRAL', 'Neutral / Base'), ('PESSIMISTIC', 'Pesimista')], default='NEUTRAL', max_length=20, verbose_name='Tipo de Versión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Financiero',
                'verbose_name_plural': 'Planes Financieros',
            },
        ),
        migrations.CreateModel(
            name='MacroAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Inflación (%)')),
                ('exchange_rate', models.DecimalField(decimal_places=3, default=3.7, max_digits=5, verbose_name='Tipo de Cambio (PEN/USD)')),
                ('gdp_growth', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Crecimiento PBI (%)')),
                ('market_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Referencia BCRP (%)')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macro_assumptions', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Supuesto Macroeconómico',
                'verbose_name_plural': 'Supuestos Macroeconómicos',
            },
        ),
        migrations.CreateModel(
            name='CommercialAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Meta de Colocaciones (Monto)')),
                ('captation_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Meta de Captaciones (Monto)')),
                ('new_members_goal', models.IntegerField(default=0, verbose_name='Meta de Nuevos Socios')),
                ('rate_consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Consumo (%)')),
                ('rate_micro', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Microempresa (%)')),
                ('rate_mortgage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Hipotecario (%)')),
                ('rate_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Ahorros (%)')),
                ('rate_dpf', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa DPF (%)')),
                ('unit', models.ForeignKey(limit_choices_to={'is_agency': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organizationalunit', verbose_name='Agencia')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_assumptions', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Supuesto Comercial',
                'verbose_name_plural': 'Supuestos Comerciales',
                'unique_together': {('plan', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='OperatingAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_increase', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Incremento Gasto Personal (%)')),
                ('fixed_costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Gastos Administrativos Fijos')),
                ('variable_cost_per_member', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Variable por Socio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_assumptions', to='financial_planning.financialplan')),
                ('unit', models.ForeignKey(limit_choices_to={'is_agency': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organizationalunit', verbose_name='Agencia')),
            ],
            options={
                'verbose_name': 'Supuesto Operativo',
                'verbose_name_plural': 'Supuestos Operativos',
                'unique_together': {('plan', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='ProjectedMonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mes Proyectado')),
                ('portfolio_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Saldo de Cartera')),
                ('deposits_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Saldo de Depósitos')),
                ('financial_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Ingresos Financieros')),
                ('financial_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Gastos Financieros')),
                ('provisions_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Gasto en Provisiones')),
                ('operating_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Gastos Operativos')),
                ('net_remanent', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Remanente Neto')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_data', to='financial_planning.financialplan')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.organizationalunit', verbose_name='Agencia / Sede')),
            ],
            options={
                'verbose_name': 'Dato Proyectado Mensual',
                'verbose_name_plural': 'Datos Proyectados Mensuales',
                'unique_together': {('plan', 'unit', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RiskAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_delinquency_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Índice de Morosidad Esperado (%)')),
                ('provision_rate_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Provisión Promedio (%)')),
                ('expected_write_offs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Castigos Estimados (Monto)')),
                ('recovery_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Recuperación (%)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assumptions', to='financial_planning.financialplan')),
                ('unit', models.ForeignKey(limit_choices_to={'is_agency': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organizationalunit', verbose_name='Agencia')),
            ],
            options={
                'verbose_name': 'Supuesto de Riesgo',
                'verbose_name_plural': 'Supuestos de Riesgo',
                'unique_together': {('plan', 'unit')},
            },
        ),
    ]
