# Generated by Django 6.0.4 on 2026-05-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_alter_activity_id_alter_company_id_and_more'),
        ('financial_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Producto')),
                ('category', models.CharField(choices=[('ASSET', 'Activo (Cartera)'), ('LIABILITY', 'Pasivo (Depósitos)')], default='ASSET', max_length=20, verbose_name='Categoría')),
                ('credit_type', models.CharField(blank=True, help_text='Ej. Consumo No Revolvente, Microempresa, Hipotecario', max_length=100, null=True, verbose_name='Tipo de Crédito')),
            ],
            options={
                'verbose_name': 'Catálogo de Producto',
                'verbose_name_plural': 'Catálogos de Productos',
            },
        ),
        migrations.AddField(
            model_name='macroassumption',
            name='unemployment_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Desempleo (%)'),
        ),
        migrations.AddField(
            model_name='operatingassumption',
            name='capex',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Inversiones CAPEX'),
        ),
        migrations.AlterField(
            model_name='riskassumption',
            name='expected_delinquency_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Índice de Mora (PD) (%)'),
        ),
        migrations.AlterField(
            model_name='riskassumption',
            name='expected_write_offs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Castigos Netos (Monto Anual)'),
        ),
        migrations.AlterField(
            model_name='riskassumption',
            name='provision_rate_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Provisión (%)'),
        ),
        migrations.CreateModel(
            name='EquityAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retained_earnings_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Retención de Excedentes (%)')),
                ('capital_contributions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Aportes de Capital (Anual)')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equity_assumptions', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Supuesto Patrimonial',
                'verbose_name_plural': 'Supuestos Patrimoniales',
            },
        ),
        migrations.CreateModel(
            name='LiquidityAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_withdrawal_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Retiro Ahorros (%)')),
                ('dpf_renewal_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa Renovación DPFs (%)')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_assumptions', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Supuesto de Liquidez',
                'verbose_name_plural': 'Supuestos de Liquidez',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_goal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Meta de Crecimiento Net (Monto Anual)')),
                ('prepayment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Prepagos (%)')),
                ('refinancing_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de Refinanciación (%)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assumptions', to='financial_planning.financialplan')),
                ('unit', models.ForeignKey(limit_choices_to={'is_agency': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organizationalunit', verbose_name='Agencia')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_planning.productcatalog', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Supuesto de Cartera/Producto',
                'verbose_name_plural': 'Supuestos de Cartera/Producto',
                'unique_together': {('plan', 'unit', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectedmonthlydata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='riskassumption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectedmonthlydata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_planning.productcatalog', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='riskassumption',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_planning.productcatalog', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='projectedmonthlydata',
            unique_together={('plan', 'unit', 'product', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='riskassumption',
            unique_together={('plan', 'unit', 'product')},
        ),
        migrations.CreateModel(
            name='RateAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa Activa para Colocaciones, Pasiva para Captaciones', max_digits=5, verbose_name='TEA / Tasa Efectiva (%)')),
                ('funding_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Costo de Fondeo Asignado (%)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_assumptions', to='financial_planning.financialplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_planning.productcatalog', verbose_name='Producto')),
                ('unit', models.ForeignKey(limit_choices_to={'is_agency': True}, on_delete=django.db.models.deletion.CASCADE, to='catalogs.organizationalunit', verbose_name='Agencia')),
            ],
            options={
                'verbose_name': 'Supuesto de Tasa',
                'verbose_name_plural': 'Supuestos de Tasas',
                'unique_together': {('plan', 'unit', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='CommercialAssumption',
        ),
    ]
