# Generated by Django 5.2.7 on 2026-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0002_productcatalog_macroassumption_unemployment_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialplan',
            name='end_date',
        ),
        migrations.AddField(
            model_name='financialplan',
            name='historical_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio de Información (Histórico)'),
        ),
        migrations.AddField(
            model_name='financialplan',
            name='projection_years',
            field=models.PositiveIntegerField(default=3, verbose_name='Años a Proyectar'),
        ),
        migrations.AlterField(
            model_name='equityassumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financialplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financialplan',
            name='start_date',
            field=models.DateField(verbose_name='Fecha Inicio de Proyección'),
        ),
        migrations.AlterField(
            model_name='liquidityassumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='macroassumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operatingassumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfolioassumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcatalog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectedmonthlydata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rateassumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskassumption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
