# Generated by Django 5.2.7 on 2026-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0003_remove_financialplan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialplan',
            name='historical_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos Históricos'),
        ),
    ]
