# Generated by Django 5.2.7 on 2026-05-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0004_financialplan_historical_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialplan',
            name='budget_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos de Presupuesto Institucional'),
        ),
    ]
