# Generated by Django 5.2.7 on 2026-05-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0005_financialplan_budget_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialplan',
            name='plan_type',
            field=models.CharField(choices=[('FINANCIAL', 'Plan Financiero'), ('INSTITUTIONAL', 'Presupuesto Institucional')], default='FINANCIAL', max_length=20, verbose_name='Tipo de Plan'),
        ),
    ]
