# Generated by Django 5.2.7 on 2026-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0006_financialplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialplan',
            name='locked_steps',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pasos Bloqueados'),
        ),
    ]
