# Generated by Django 5.2.7 on 2026-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0007_financialplan_locked_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialplan',
            name='annual_goals',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metas Anuales'),
        ),
    ]
