# Generated by Django 5.2.7 on 2026-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0008_financialplan_annual_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialplan',
            name='trend_analysis_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Análisis de Tendencias y Escenarios'),
        ),
    ]
