# Generated by Django 6.0.4 on 2026-06-16 18:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0009_financialplan_trend_analysis_data'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='LiquidityAssumption',),
        migrations.DeleteModel(name='OperatingAssumption',),
        migrations.DeleteModel(name='ProjectedMonthlyData',),
        migrations.DeleteModel(name='RateAssumption',),
        migrations.DeleteModel(name='PortfolioAssumption',),
        migrations.DeleteModel(name='MacroAssumption',),
        migrations.DeleteModel(name='RiskAssumption',),
        migrations.DeleteModel(name='EquityAssumption',),
        migrations.DeleteModel(name='FinancialPlan',),
        migrations.DeleteModel(name='ProductCatalog',),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Cuenta')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=20)),
                ('nivel', models.PositiveIntegerField(verbose_name='Nivel de Profundidad')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='financial_planning.cuentacontable', verbose_name='Cuenta Padre')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'unique_together': {('organization', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveIntegerField(verbose_name='Mes')),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('FINAL', 'Definitivo')], default='DRAFT', max_length=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Periodo Financiero',
                'verbose_name_plural': 'Periodos Financieros',
                'unique_together': {('organization', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='BalanceDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('analisis_vertical', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Análisis Vertical')),
                ('analisis_horizontal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='% Análisis Horizontal (Crecimiento)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='financial_planning.cuentacontable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='financial_planning.periodofinanciero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('anio_base', models.PositiveIntegerField(verbose_name='Año Base')),
                ('horizonte_anios', models.PositiveIntegerField(default=3, verbose_name='Horizonte (Años)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Plan Financiero',
                'verbose_name_plural': 'Planes Financieros',
                'unique_together': {('organization', 'nombre')},
            },
        ),
    ]
