# Generated by Django 6.0.4 on 2026-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0010_remove_liquidityassumption_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfinanciero',
            name='historical_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Data Histórica'),
        ),
    ]
