# Generated by Django 6.0.4 on 2026-06-23 13:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0011_planfinanciero_historical_data'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Plan')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Financial Plan',
                'verbose_name_plural': 'Financial Plans',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, verbose_name='Periodo (YYYY-MM)')),
                ('account_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Dato Histórico',
                'verbose_name_plural': 'Datos Históricos',
                'unique_together': {('organization', 'plan', 'period', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='MacroAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mes de Proyección')),
                ('inflation_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_assumptions', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Supuesto Macroeconómico',
                'verbose_name_plural': 'Supuestos Macroeconómicos',
                'unique_together': {('organization', 'plan', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PlanAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CREDIT_PORTFOLIO', 'Cartera de Créditos'), ('DELINQUENCY', 'Mora'), ('SAVINGS', 'Ahorros'), ('DPF', 'DPF'), ('CONTRIBUTIONS', 'Aportes')], max_length=50)),
                ('trend_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Tasa de Tendencia')),
                ('optimistic_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Escenario Optimista')),
                ('pessimistic_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Escenario Pesimista')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assumptions', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Supuesto de Plan',
                'verbose_name_plural': 'Supuestos de Plan',
                'unique_together': {('organization', 'plan', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProjectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mes Proyectado (1 a N)')),
                ('scenario', models.CharField(choices=[('BASE', 'Base (Tendencia)'), ('OPTIMISTIC', 'Optimista'), ('PESSIMISTIC', 'Pesimista')], default='BASE', max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projected_data', to='financial_planning.financialplan')),
            ],
            options={
                'verbose_name': 'Dato Proyectado',
                'verbose_name_plural': 'Datos Proyectados',
                'unique_together': {('organization', 'plan', 'month', 'scenario', 'account_name')},
            },
        ),
    ]
