# Generated by Django 6.0.4 on 2026-06-25 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0012_financialplan_historicaldata_macroassumption_and_more'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionEscenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(default='Consolidado', max_length=100)),
                ('variable_id', models.CharField(max_length=100)),
                ('variable_name', models.CharField(max_length=255)),
                ('tasa_tendencia', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tasa_base', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tasa_pesimista', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tasa_optimista', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='financial_planning.planfinanciero')),
            ],
            options={
                'verbose_name': 'Simulación Escenario',
                'verbose_name_plural': 'Simulaciones Escenarios',
                'unique_together': {('organization', 'plan', 'agencia', 'variable_id')},
            },
        ),
        migrations.CreateModel(
            name='ProyeccionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_proyeccion', models.PositiveIntegerField()),
                ('valor_tendencia', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('valor_pesimista', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('valor_optimista', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('mc_valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mc_valor_pesimista', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mc_valor_optimista', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='financial_planning.simulacionescenario')),
            ],
            options={
                'verbose_name': 'Proyección Mensual',
                'verbose_name_plural': 'Proyecciones Mensuales',
                'ordering': ['mes_proyeccion'],
                'unique_together': {('organization', 'escenario', 'mes_proyeccion')},
            },
        ),
    ]
