# Generated by Django 6.0.4 on 2026-06-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0013_simulacionescenario_proyeccionmensual'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ING_FIN', 'Ingresos Financieros'), ('ING_SERV', 'Ingresos por Servicios Financieros'), ('OTROS_ING', 'Otros Ingresos'), ('GAS_FIN', 'Gastos Financieros'), ('GAS_SERV', 'Gastos por Servicios Financieros'), ('PROV', 'Provisiones'), ('DEP_AMORT', 'Depreciación y Amortización'), ('GAS_ADMIN', 'Gastos Administrativos'), ('OTROS_EG', 'Otros Egresos')], max_length=20)),
                ('account_mapping', models.ManyToManyField(blank=True, related_name='budget_items', to='financial_planning.cuentacontable')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Rubro Presupuestal',
                'verbose_name_plural': 'Rubros Presupuestales',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('scenario', models.CharField(choices=[('BASE', 'Base'), ('OPTIMISTIC', 'Optimista'), ('PESSIMISTIC', 'Pesimista')], default='BASE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobado'), ('CLOSED', 'Cerrado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan_financiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_versions', to='financial_planning.planfinanciero')),
            ],
            options={
                'verbose_name': 'Versión de Presupuesto',
                'verbose_name_plural': 'Versiones de Presupuesto',
                'unique_together': {('organization', 'plan_financiero', 'scenario', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_calculation_type', models.CharField(max_length=20)),
                ('total_amount_y1', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_amount_y2', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_amount_y3', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='financial_planning.budgetitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financial_planning.budgetversion')),
            ],
            options={
                'verbose_name': 'Línea de Presupuesto',
                'verbose_name_plural': 'Líneas de Presupuesto',
                'unique_together': {('organization', 'version', 'item')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('MANUAL', 'Ingreso Manual'), ('TREND', 'Tendencia Histórica'), ('DRIVER', 'Basado en Driver/Tasa'), ('COPY', 'Copia Año Anterior')], default='MANUAL', max_length=20)),
                ('source_trend_variable', models.CharField(blank=True, max_length=100, null=True)),
                ('assumption_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='financial_planning.budgetitem')),
            ],
            options={
                'verbose_name': 'Regla de Cálculo Presupuestal',
                'verbose_name_plural': 'Reglas de Cálculo Presupuestal',
                'unique_together': {('organization', 'item')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('MONTH', 'Mes'), ('YEAR', 'Año')], max_length=10)),
                ('period_index', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='financial_planning.budgetline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
            ],
            options={
                'verbose_name': 'Detalle de Línea Presupuestal',
                'verbose_name_plural': 'Detalles de Línea Presupuestal',
                'ordering': ['period_type', 'period_index'],
                'unique_together': {('organization', 'budget_line', 'period_type', 'period_index')},
            },
        ),
    ]
