# Generated by Django 6.0.4 on 2026-07-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0014_budgetitem_budgetversion_budgetline_and_more'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetversion',
            name='scenario',
            field=models.CharField(choices=[('BASE', 'Base (Tendencia)'), ('OPTIMISTIC', 'Optimista (Tendencia)'), ('PESSIMISTIC', 'Pesimista (Tendencia)'), ('MC_BASE', 'Base (Montecarlo)'), ('MC_OPTIMISTIC', 'Optimista (Montecarlo)'), ('MC_PESSIMISTIC', 'Pesimista (Montecarlo)')], default='BASE', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectedBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(default='BASE', max_length=20)),
                ('account_code', models.CharField(max_length=50)),
                ('adjustments', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_adjustments', to='financial_planning.planfinanciero')),
            ],
            options={
                'verbose_name': 'Ajuste de Balance Proyectado',
                'verbose_name_plural': 'Ajustes de Balance Proyectado',
                'unique_together': {('organization', 'plan', 'scenario', 'account_code')},
            },
        ),
    ]
