# Generated by Django 6.0.4 on 2026-07-07 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0015_alter_budgetversion_scenario_and_more'),
        ('users', '0008_organization_alter_auditlog_id_alter_role_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectedBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=20)),
                ('data', models.JSONField(verbose_name='Datos Calculados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization', verbose_name='Cooperativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_snapshots', to='financial_planning.planfinanciero')),
            ],
            options={
                'verbose_name': 'Snapshot de Balance Proyectado',
                'verbose_name_plural': 'Snapshots de Balance Proyectado',
                'unique_together': {('organization', 'plan', 'scenario')},
            },
        ),
    ]
