# Generated by Django 6.0.5 on 2026-07-15 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, verbose_name='Nivel (1-5)')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre (Ej: Catastrófico)')),
                ('description', models.TextField(blank=True, null=True)),
                ('financial_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Umbral económico de pérdida referencial', max_digits=15)),
            ],
            options={
                'verbose_name': 'Nivel de Impacto',
                'verbose_name_plural': 'Niveles de Impacto',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ProbabilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, verbose_name='Nivel (1-5)')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre (Ej: Posible)')),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Peso para cálculos si aplica', max_digits=5)),
            ],
            options={
                'verbose_name': 'Nivel de Probabilidad',
                'verbose_name_plural': 'Niveles de Probabilidad',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Categoría de Riesgo')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Riesgo',
                'verbose_name_plural': 'Categorías de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='Macroprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Macroproceso')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_macroprocesses', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Macroproceso')),
            ],
            options={
                'verbose_name': 'Macroproceso',
                'verbose_name_plural': 'Macroprocesos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Proceso')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('criticality', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=20, verbose_name='Criticidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macroprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='op_risk.macroprocess', verbose_name='Macroproceso')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_processes', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Proceso')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['macroprocess', 'name'],
            },
        ),
    ]
