# Generated by Django 6.0.5 on 2026-07-15 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('op_risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactlevel',
            name='financial_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Umbral económico', max_digits=15),
        ),
        migrations.AlterField(
            model_name='probabilitylevel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso para cálculos', max_digits=5),
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Hallazgo/Plan')),
                ('description', models.TextField(verbose_name='Acción Correctiva')),
                ('commitment_date', models.DateField(verbose_name='Fecha Compromiso')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('OVERDUE', 'Atrasado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_action_plans', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Plan de Acción',
                'verbose_name_plural': 'Planes de Acción',
            },
        ),
        migrations.CreateModel(
            name='ActionPlanEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='op_risk/evidences/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='op_risk.actionplan')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyRiskIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del KRI')),
                ('description', models.TextField(blank=True, null=True)),
                ('green_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umbral Verde (<=)')),
                ('yellow_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umbral Amarillo (<=)')),
                ('red_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umbral Rojo (>)')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_owned_kris', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kris', to='op_risk.process')),
            ],
            options={
                'verbose_name': 'KRI',
                'verbose_name_plural': 'KRIs',
            },
        ),
        migrations.CreateModel(
            name='KRIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Lectura')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('notes', models.TextField(blank=True, null=True)),
                ('kri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='op_risk.keyriskindicator')),
            ],
            options={
                'verbose_name': 'Lectura de KRI',
                'verbose_name_plural': 'Lecturas de KRIs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OpRiskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('file', models.FileField(upload_to='op_risk/documents/')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento RO',
                'verbose_name_plural': 'Documentos RO',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Riesgo')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='Causa')),
                ('event', models.TextField(blank=True, null=True, verbose_name='Evento')),
                ('consequence', models.TextField(blank=True, null=True, verbose_name='Impacto/Consecuencia')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REVIEW', 'En Revisión'), ('APPROVED', 'Aprobado'), ('CLOSED', 'Cerrado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='op_risk.riskcategory', verbose_name='Categoría de Riesgo')),
                ('inherent_impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_inherent_imp', to='op_risk.impactlevel', verbose_name='Impacto Inherente')),
                ('inherent_probability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_inherent_prob', to='op_risk.probabilitylevel', verbose_name='Probabilidad Inherente')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Riesgo')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='op_risk.process', verbose_name='Proceso')),
                ('residual_impact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_residual_imp', to='op_risk.impactlevel', verbose_name='Impacto Residual')),
                ('residual_probability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_residual_prob', to='op_risk.probabilitylevel', verbose_name='Probabilidad Residual')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
            },
        ),
        migrations.AddField(
            model_name='keyriskindicator',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kris', to='op_risk.risk'),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Control')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('DETECTIVE', 'Detectivo'), ('CORRECTIVE', 'Correctivo')], default='PREVENTIVE', max_length=20, verbose_name='Tipo de Control')),
                ('periodicity', models.CharField(help_text='Ej: Diario, Mensual', max_length=100, verbose_name='Periodicidad')),
                ('design_efficacy', models.IntegerField(default=100, verbose_name='Eficacia del Diseño (%)')),
                ('operational_effectiveness', models.IntegerField(default=100, verbose_name='Efectividad Operativa (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_owned_controls', to=settings.AUTH_USER_MODEL, verbose_name='Dueño del Control')),
                ('risks', models.ManyToManyField(blank=True, related_name='controls', to='op_risk.risk', verbose_name='Riesgos Mitigados')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controles',
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='op_risk.risk'),
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('event_type', models.CharField(choices=[('LOSS', 'Pérdida'), ('NEAR_MISS', 'Cuasi Pérdida'), ('SYSTEM_FAILURE', 'Falla de Sistema'), ('FRAUD', 'Fraude')], max_length=20, verbose_name='Tipo de Evento')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Monto de Pérdida')),
                ('date_occurred', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('date_discovered', models.DateField(verbose_name='Fecha de Descubrimiento')),
                ('root_cause', models.TextField(blank=True, null=True, verbose_name='Causa Raíz')),
                ('immediate_action', models.TextField(blank=True, null=True, verbose_name='Acción Tomada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('failed_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_in_events', to='op_risk.control', verbose_name='Control Fallido')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='op_risk.process', verbose_name='Proceso Afectado')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_reported_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Riesgo',
                'verbose_name_plural': 'Eventos de Riesgo',
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='op_risk.riskevent'),
        ),
        migrations.CreateModel(
            name='Subprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Subproceso')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_subprocesses', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesses', to='op_risk.process', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Subproceso',
                'verbose_name_plural': 'Subprocesos',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Actividad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_activities', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
                ('subprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='op_risk.subprocess', verbose_name='Subproceso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
