# Generated by Django 6.0.5 on 2026-07-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_risk', '0002_alter_impactlevel_financial_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales (Custom Fields)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales (Custom Fields)'),
        ),
        migrations.AddField(
            model_name='riskevent',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales (Custom Fields)'),
        ),
    ]
