# Generated by Django 6.0.5 on 2026-07-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_risk', '0003_control_extra_data_risk_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCapitalCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Año de Cálculo')),
                ('gross_income_y1', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ingresos Brutos (Año - 1)')),
                ('gross_income_y2', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ingresos Brutos (Año - 2)')),
                ('gross_income_y3', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ingresos Brutos (Año - 3)')),
                ('alfa_factor', models.DecimalField(decimal_places=4, default=0.15, max_digits=5, verbose_name='Factor Alfa (Ej: 15%)')),
                ('calculated_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Capital Requerido Calculado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cálculo Capital Operacional',
                'verbose_name_plural': 'Cálculos Capital Operacional',
                'ordering': ['-year'],
            },
        ),
    ]
