# Generated by Django 6.0.5 on 2026-07-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_position_department'),
        ('op_risk', '0004_operationalcapitalcalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='macroprocess',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='process',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subprocess',
            name='owner',
        ),
        migrations.AddField(
            model_name='activity',
            name='owner_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_activities_area', to='catalogs.organizationalunit', verbose_name='Área Dueña'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_activities', to='catalogs.position', verbose_name='Cargo Dueño'),
        ),
        migrations.AddField(
            model_name='macroprocess',
            name='owner_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_macroprocesses_area', to='catalogs.organizationalunit', verbose_name='Área Dueña'),
        ),
        migrations.AddField(
            model_name='macroprocess',
            name='owner_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_macroprocesses', to='catalogs.position', verbose_name='Cargo Dueño'),
        ),
        migrations.AddField(
            model_name='process',
            name='owner_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_processes_area', to='catalogs.organizationalunit', verbose_name='Área Dueña'),
        ),
        migrations.AddField(
            model_name='process',
            name='owner_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_processes', to='catalogs.position', verbose_name='Cargo Dueño'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='owner_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_subprocesses_area', to='catalogs.organizationalunit', verbose_name='Área Dueña'),
        ),
        migrations.AddField(
            model_name='subprocess',
            name='owner_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_subprocesses', to='catalogs.position', verbose_name='Cargo Dueño'),
        ),
    ]
