# Generated by Django 6.0.5 on 2026-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_risk', '0005_remove_activity_owner_remove_macroprocess_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opriskdocument',
            name='drive_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Drive/Nube'),
        ),
        migrations.AlterField(
            model_name='opriskdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='op_risk/documents/', verbose_name='Archivo Local'),
        ),
    ]
