# Generated by Django 6.0.5 on 2026-07-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_systemintegration'),
        ('op_risk', '0006_opriskdocument_drive_url_alter_opriskdocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código Interno (Ej: DRAFT, APPROVED)')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre (Ej: Borrador, Aprobado)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado del Riesgo',
                'verbose_name_plural': 'Estados del Riesgo',
            },
        ),
        migrations.RemoveField(
            model_name='risk',
            name='owner',
        ),
        migrations.AddField(
            model_name='risk',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_owned_risks', to='catalogs.position', verbose_name='Dueño del Riesgo'),
        ),
        migrations.RemoveField(
            model_name='risk',
            name='status',
        ),
        migrations.AddField(
            model_name='risk',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='op_risk.riskstatus', verbose_name='Estado'),
        ),
    ]
