# Generated by Django 6.0.5 on 2026-07-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_systemintegration'),
        ('op_risk', '0007_riskstatus_alter_risk_owner_alter_risk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_owned_risks', to='catalogs.position', verbose_name='Dueño del Cargo'),
        ),
    ]
