# Generated by Django 6.0.5 on 2026-07-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_auto_20260715_1140'),
        ('op_risk', '0010_alter_control_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskevent',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_reported_events', to='catalogs.position', verbose_name='Responsable'),
        ),
    ]
