# Generated by Django 6.0.5 on 2026-07-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_auto_20260715_1140'),
        ('op_risk', '0011_alter_riskevent_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyriskindicator',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='keyriskindicator',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_owned_kris', to='catalogs.position', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='keyriskindicator',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kris', to='op_risk.process', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='keyriskindicator',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kris', to='op_risk.risk', verbose_name='Riesgo'),
        ),
    ]
