# Generated by Django 6.0.5 on 2026-07-15 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_auto_20260715_1140'),
        ('op_risk', '0012_alter_keyriskindicator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='op_risk.riskevent', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oprisk_action_plans', to='catalogs.position', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='op_risk.risk', verbose_name='Riesgo'),
        ),
    ]
