# Generated by Django 6.0.5 on 2026-07-15 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_auto_20260715_1140'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('op_risk', '0013_alter_actionplan_event_alter_actionplan_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opriskdocument',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Registro Relacionado'),
        ),
        migrations.AlterField(
            model_name='opriskdocument',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID del Registro'),
        ),
        migrations.AlterField(
            model_name='opriskdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.position', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='opriskdocument',
            name='version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Versión'),
        ),
    ]
