# Generated by Django 6.0.5 on 2026-07-15 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('op_risk', '0014_alter_opriskdocument_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opriskdocument',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Registro Relacionado'),
        ),
        migrations.AlterField(
            model_name='opriskdocument',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Registro'),
        ),
    ]
