# Generated by Django 6.0.4 on 2026-04-28 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpRiskEventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Categoría de Evento')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Evento Operacional',
                'verbose_name_plural': 'Categorías de Evento Operacional',
            },
        ),
        migrations.CreateModel(
            name='OpRiskIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Incidente')),
                ('description', models.TextField(verbose_name='Descripción del Incidente')),
                ('incident_date', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('discovery_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Descubrimiento')),
                ('severity', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], max_length=20, verbose_name='Severidad')),
                ('gross_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pérdida Bruta Estimada')),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Recuperado')),
                ('net_loss', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Pérdida Neta')),
                ('root_cause_analysis', models.TextField(blank=True, verbose_name='Análisis de Causa Raíz')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operational_risk.opriskeventcategory', verbose_name='Categoría')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.process', verbose_name='Proceso Afectado')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente de Riesgo Operacional',
                'verbose_name_plural': 'Incidentes de Riesgo Operacional',
            },
        ),
    ]
