# Generated by Django 6.0.4 on 2026-04-29 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opriskincident',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('mitigated', 'Mitigado'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='opriskincident',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operational_risk.opriskeventcategory', verbose_name='Categoría Basilea'),
        ),
        migrations.AlterField(
            model_name='opriskincident',
            name='discovery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Descubrimiento'),
        ),
        migrations.AlterField(
            model_name='opriskincident',
            name='gross_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pérdida Bruta (S/)'),
        ),
        migrations.AlterField(
            model_name='opriskincident',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título del Evento'),
        ),
    ]
