# Generated by Django 5.2.7 on 2026-05-12 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0002_opriskincident_status_alter_opriskincident_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='COSOComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Componente COSO')),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Componente COSO',
                'verbose_name_plural': 'Componentes COSO',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='opriskeventcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opriskincident',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='COSOPrinciple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Principio')),
                ('description', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principles', to='operational_risk.cosocomponent')),
            ],
            options={
                'verbose_name': 'Principio COSO',
                'verbose_name_plural': 'Principios COSO',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='COSOAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Evaluación')),
                ('score', models.IntegerField(choices=[(4, 'Muy Favorable'), (3, 'Favorable'), (2, 'Poco Favorable'), (1, 'Sin Registro')], default=1, verbose_name='Nivel de Madurez')),
                ('evidence', models.TextField(blank=True, verbose_name='Evidencia / Sustento')),
                ('gap_analysis', models.TextField(blank=True, verbose_name='Análisis de Brechas')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='operational_risk.cosoprinciple')),
            ],
            options={
                'verbose_name': 'Evaluación COSO',
                'verbose_name_plural': 'Evaluaciones COSO',
                'unique_together': {('principle', 'evaluation_date')},
            },
        ),
    ]
