# Generated by Django 5.2.7 on 2026-05-12 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_organizationalunit_id_alter_parameter_id_and_more'),
        ('operational_risk', '0003_cosocomponent_alter_opriskeventcategory_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código')),
                ('detection_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Detección')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('loss_type', models.CharField(max_length=100, verbose_name='Tipo de Pérdida')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Estimado')),
                ('currency', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('preliminary', 'Preliminar'), ('review', 'En Revisión'), ('linked', 'Vinculada'), ('adjusted', 'Ajustada'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='preliminary', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='potential_losses/', verbose_name='Evidencia Adjunta')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('linking_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Vinculación')),
                ('recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Recuperado')),
                ('gross_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Bruto Final')),
                ('net_loss', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Monto Neto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.organizationalunit', verbose_name='Área/Unidad')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_losses', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_losses', to='operational_risk.opriskincident', verbose_name='Evento Relacionado')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.process', verbose_name='Proceso')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_losses', to=settings.AUTH_USER_MODEL)),
                ('subprocess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.subprocess', verbose_name='Subproceso')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_losses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posible Pérdida',
                'verbose_name_plural': 'Posibles Pérdidas',
            },
        ),
        migrations.CreateModel(
            name='PotentialLossAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='operational_risk.potentialloss')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
