# Generated by Django 5.2.7 on 2026-05-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0004_potentialloss_potentiallossaudit'),
        ('risks', '0002_alter_risk_id_alter_riskassessment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opriskincident',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='risks.risk', verbose_name='Riesgo Asociado'),
        ),
    ]
