# Generated by Django 5.2.7 on 2026-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0005_opriskincident_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagementStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Etapa')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción Corta')),
                ('instruction', models.TextField(verbose_name='Instrucciones Detalladas (Manual)')),
                ('url_name', models.CharField(max_length=100, verbose_name='Nombre de la URL (Django)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('icon', models.CharField(default='fas fa-step-forward', max_length=50, verbose_name='Icono FontAwesome')),
            ],
            options={
                'verbose_name': 'Etapa del Ciclo de Gestión',
                'verbose_name_plural': 'Etapas del Ciclo de Gestión',
                'ordering': ['order'],
            },
        ),
    ]
