# Generated by Django 5.2.7 on 2026-05-13 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0007_alter_cosoassessment_id_alter_cosocomponent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCycleSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Cierre')),
                ('cycle_name', models.CharField(max_length=100, verbose_name='Nombre del Ciclo/Mes')),
                ('maturity_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nivel de Madurez (%)')),
                ('avg_residual_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Riesgo Residual Promedio')),
                ('high_risks_count', models.IntegerField(verbose_name='Cant. Riesgos Críticos')),
                ('total_gross_loss', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Pérdida Bruta Acumulada')),
                ('plan_compliance_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cumplimiento de Planes (%)')),
                ('comments', models.TextField(blank=True, verbose_name='Observaciones del Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot de Ciclo de Riesgo',
                'verbose_name_plural': 'Snapshots de Ciclo de Riesgo',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AlterField(
            model_name='cosoassessment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cosocomponent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cosoprinciple',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opriskeventcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opriskincident',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='potentialloss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='potentiallossaudit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskmanagementstep',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
