# Generated by Django 5.2.7 on 2026-05-13 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_company_management_alter_organizationalunit_options_and_more'),
        ('operational_risk', '0008_riskcyclesnapshot_alter_cosoassessment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opriskincident',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.activity', verbose_name='Actividad Afectada'),
        ),
        migrations.AddField(
            model_name='opriskincident',
            name='subprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.subprocess', verbose_name='Subproceso Afectado'),
        ),
    ]
