# Generated by Django 5.2.7 on 2026-05-12 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0002_alter_controltest_id_alter_riskcontrol_id'),
        ('risks', '0002_alter_risk_id_alter_riskassessment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Acción')),
                ('description', models.TextField(verbose_name='Descripción de la Tarea')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('progress', models.IntegerField(default=0, verbose_name='Progreso (%)')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='controls.riskcontrol')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_actions', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='risks.risk')),
            ],
            options={
                'verbose_name': 'Plan de Acción',
                'verbose_name_plural': 'Planes de Acción',
            },
        ),
        migrations.CreateModel(
            name='ActionFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Seguimiento')),
                ('comment', models.TextField(verbose_name='Comentario / Avance')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='action_plans/evidence/', verbose_name='Evidencia')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='action_plans.actionplan')),
            ],
            options={
                'verbose_name': 'Seguimiento de Acción',
                'verbose_name_plural': 'Seguimientos de Acción',
            },
        ),
    ]
