# Generated by Django 5.2.7 on 2026-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0002_alter_actionfollowup_id_alter_actionplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionfollowup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
