# Generated by Django 6.0.4 on 2026-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0003_alter_actionfollowup_id_alter_actionplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionfollowup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
