# Generated by Django 6.0.4 on 2026-04-28 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KRICatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código KRI')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('risk_type', models.CharField(max_length=100, verbose_name='Tipo de Riesgo')),
                ('formula', models.TextField(verbose_name='Fórmula de Cálculo')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('frequency', models.CharField(max_length=50, verbose_name='Frecuencia')),
                ('data_source', models.CharField(max_length=255, verbose_name='Fuente de Datos')),
                ('kri_level', models.CharField(choices=[('L1', 'Nivel 1 (Institucional)'), ('L2', 'Nivel 2 (Negocio/Operativo)')], max_length=10, verbose_name='Tipo de Indicador')),
                ('direction', models.CharField(choices=[('UP', 'Mayor es peor'), ('DOWN', 'Menor es peor'), ('RANGE', 'Fuera de Rango es peor')], max_length=10, verbose_name='Sentido')),
            ],
            options={
                'verbose_name': 'Catálogo de KRI',
                'verbose_name_plural': 'Catálogo de KRIs',
            },
        ),
        migrations.CreateModel(
            name='RAFFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Marco')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobado'), ('EXPIRED', 'Vencido'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('approved_by', models.CharField(blank=True, max_length=255, verbose_name='Aprobado por')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación')),
            ],
            options={
                'verbose_name': 'Marco de Apetito (RAF)',
                'verbose_name_plural': 'Marcos de Apetito (RAF)',
            },
        ),
        migrations.CreateModel(
            name='KRIMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_off_date', models.DateField(verbose_name='Fecha de Corte')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor Medido')),
                ('semaphore', models.CharField(choices=[('GREEN', 'Verde (Objetivo)'), ('YELLOW', 'Amarillo (Preventiva)'), ('ORANGE', 'Naranja (Tolerancia Excedida)'), ('RED', 'Rojo (Crítica / Capacidad)')], max_length=20, verbose_name='Estado Semáforo')),
                ('deviation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desviación (%)')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('kri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_appetite.kricatalog')),
                ('loaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición de KRI',
                'verbose_name_plural': 'Mediciones de KRIs',
            },
        ),
        migrations.CreateModel(
            name='RAFBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_type', models.CharField(max_length=100, verbose_name='Tipo de Exceso')),
                ('event_date', models.DateField(verbose_name='Fecha de Evento')),
                ('severity', models.CharField(max_length=50, verbose_name='Severidad')),
                ('cause', models.TextField(verbose_name='Causa')),
                ('impact', models.TextField(verbose_name='Impacto')),
                ('required_action', models.TextField(verbose_name='Acción Requerida')),
                ('due_date', models.DateField(verbose_name='Fecha Compromiso')),
                ('state', models.CharField(choices=[('OPEN', 'Abierto'), ('ANALYZING', 'En Análisis'), ('REMEDIATING', 'En Remediación'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_appetite.krimeasurement')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exceso de Límite (Breach)',
                'verbose_name_plural': 'Excesos de Límites (Breaches)',
            },
        ),
        migrations.CreateModel(
            name='RAFActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Acción')),
                ('response_type', models.CharField(max_length=100, verbose_name='Tipo de Respuesta')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('effectiveness', models.TextField(blank=True, verbose_name='Efectividad')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('breach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='risk_appetite.rafbreach')),
            ],
            options={
                'verbose_name': 'Plan de Acción (RAF)',
                'verbose_name_plural': 'Planes de Acción (RAF)',
            },
        ),
        migrations.CreateModel(
            name='RAFChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100, verbose_name='Entidad')),
                ('entity_id', models.IntegerField(verbose_name='ID Entidad')),
                ('field', models.CharField(max_length=100, verbose_name='Campo')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Valor Nuevo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Cambios RAF',
                'verbose_name_plural': 'Logs de Cambios RAF',
            },
        ),
        migrations.CreateModel(
            name='RAFApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=100, verbose_name='Instancia (Comité/Directorio)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('decision', models.CharField(max_length=50, verbose_name='Decisión')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_appetite.rafframework')),
            ],
            options={
                'verbose_name': 'Aprobación RAF',
                'verbose_name_plural': 'Aprobaciones RAF',
            },
        ),
        migrations.CreateModel(
            name='RAFStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=100, verbose_name='Tipo de Riesgo')),
                ('application_level', models.CharField(default='Global', max_length=100, verbose_name='Nivel de Aplicación')),
                ('qualitative_statement', models.TextField(verbose_name='Declaración Cualitativa')),
                ('risk_posture', models.CharField(choices=[('CONSERVATIVE', 'Conservador'), ('MODERATE', 'Moderado'), ('SELECTIVE', 'Selectivo'), ('ZERO_TOLERANCE', 'Cero Tolerancia')], max_length=50, verbose_name='Postura de Riesgo')),
                ('strategic_objective', models.CharField(blank=True, max_length=255, verbose_name='Objetivo Estratégico')),
                ('valid_from', models.DateField(verbose_name='Vigencia Desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Vigencia Hasta')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='risk_appetite.rafframework')),
            ],
            options={
                'verbose_name': 'Declaración de Apetito',
                'verbose_name_plural': 'Declaraciones de Apetito',
            },
        ),
        migrations.CreateModel(
            name='RAFThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(default='Institución', max_length=100, verbose_name='Alcance (Institución/Unidad)')),
                ('scope_id', models.CharField(blank=True, max_length=100, verbose_name='ID de Alcance')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor Objetivo')),
                ('green_threshold', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Umbral Verde (Apetito)')),
                ('yellow_threshold', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Umbral Amarillo (Alerta Temprana)')),
                ('orange_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Umbral Naranja (Preventivo)')),
                ('red_threshold', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Umbral Rojo (Tolerancia Excedida)')),
                ('capacity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valor Capacidad Máxima')),
                ('observation', models.TextField(blank=True, verbose_name='Observación')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='risk_appetite.rafframework')),
                ('kri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_appetite.kricatalog')),
            ],
            options={
                'verbose_name': 'Umbral de Apetito',
                'verbose_name_plural': 'Umbrales de Apetito',
            },
        ),
    ]
